- BOJ/Data_Structure/1158-요세푸스_문제-YJ.py
https://www.acmicpc.net/problem/1158
> [BOJ-1158] YJ

- Programmers/로또의 최고 순위와 최저 순위-NY.py
- 로또의 최고 순위와 최저 순위(re)-NY.py
* 처음에 풀고 나서 다른 사람들 풀이 휘리릭 보고 마지막 answer 등수 계산을 너무 복잡하게 한 것 같아서 바꿨습니다
> [Programmers-로또의 최고 순위와 최저 순위] NY

- BOJ/Data_Structure/10828-스택-NY.py
https://www.acmicpc.net/source/37561130
예전 풀이는 C로 엄청 복잡하게 풀었었는데 이번에 다시 풀면서 파이썬으로 엄청 간단하게 푼듯..
예전풀이: https://www.acmicpc.net/source/26750221
간단한 대신 C로 풀었을땐 4ms였는데 파이썬은 84ms
> [210114] NY

- BOJ/Data_Structure/10828-스택-YJ.py
https://www.acmicpc.net/source/37562116
> [2022.01.14] YJ

- Programmers/신규_아이디_추천-YJ.py
> [220115] YJ

- Programmers/신규 아이디 추천-NY.py
시간 복잡도 줄이고 싶어서(for문이나 while문 1번만 돌려고) 엄청.. 머리 굴렸어요...
잘했는지는 모르겠쥐만..
> [2022.01.15] NY

- Programmers/신규_아이디_추천-MH.py
파이썬 list 다루는 것도 기억 안나서 2시간 30분동안 열심히 구글링했어요
거의 1학년때 짠 코드랑 비슷한 듯
공부 열심히 해야겠다 ^^.... 아자작...
> [220115] MH

- Programmers/신규_아이디_추천-GH.py
어제 새벽에 올렸다가 commit 메세지 실수로 냅다 다 지워버린 여성 ^^...
정규표현식으로 써야 하는 걸 알았고... 그치만 다 까먹어서 다시 공부하다가
기 빨려서 ㅇㅇ 안 해 줄게 하고 밑에는 그냥 나의 지식으로만 채웟다...
그나저나 파이썬... 배운 게 맞ㅇ을까... while과 for문 말고는 쓸 수 있는 게 없달까...
여튼.. 미숙한 조작법으로 인해 너무 늦어서 죄송합니다.. 엉엉. 감사합니다.
> [220115] GH

- Programmers/신규_아이디_추천-YJ.py
- Sunday/Longest_Common_Prefix-YJ.py
정규식이 나라다
https://asxpyn.tistory.com/99#none
정규표현식 블로그에 정리한 것도 두고 갑니다 총총
> [220116] YJ

- Sunday/220116-NY.py
https://leetcode.com/problems/longest-common-prefix/
이 문제인데영 님들두 한번씩.. 풀어보는것..도..? 
문제는 간단한데 제가 바보라서 겁나 겁나 오래걸렸어요 엄청 많이 틀림 시무룩
> [220116] NY

- Sunday/Longest_Common_Prefix-YJ.py
https://leetcode.com/problems/longest-common-prefix
리트코드 처음 풀어봤는데 형식.. 불편.. 🥲
> [220116] YJ -2

- Programmers/신규_아이디_추천-MH.py
내가 정말 쓸데없이 돌고 돌아 짰구나
정규식은 제쳐두고 내 선에서 가장 간결하게 업데이트했어요
유진언니 블로그보고 정규식 공부하러 가야지
> [220116] MH

- BOJ/Data_Structure/9012-괄호-MH.py
자료구조.. 그 때 기억을 떠올려 stack
예전에 C++로 풀었을 떄는 stack 구조도 다 코딩했었는디..
https://www.acmicpc.net/source/25983235
근데 C++로 짠거 4ms고 이번에 76ms 걸린거 안비밀..
> [220117] MH

- BOJ/Data_Structure/9012-괄호-YJ.py
https://www.acmicpc.net/source/37707974
rstrip 빼먹어서 한번 틀렸네유
> [220117] YJ

- BOJ/Data_Structure/9012-괄호-GH.py
음...
저는 아는 게 없어서
스택(인 척하는 리스트)으로 풀어 봣습니다.. 이상입니다.
[0.76ms] https://www.acmicpc.net/source/37689096
> [220117] GH

- Programmers/숫자_문자열과_영단어-MH.py
흠냐냥 딕셔너리가 제일 효율적인 것 같아서 했는데 다른 분들의 코드도 궁금하군용
> [220118] MH

- Programmers/숫자_문자열과_영단어-NY.py
> [220118] NY

- Programmers/숫자_문자열과_영단어-YJ.py
https://programmers.co.kr/learn/courses/30/lessons/81301
> [220118] YJ

- Programmers/숫자_문자열과_영단어-GH.py
- Programmers/신규_아이디_추천-GH.py
어...
사전에 추가한 거 말곤 할 말이 없습니다..
전...................................
지금 혈중 알코올 농도 과다라서
안뇽...
> [220118] GH

- BOJ/Data_Structure/18258-큐2-YJ.py
https://www.acmicpc.net/source/37795093
저번이랑 비슷하게 풀어버렸어요
> [220119] YJ

- BOJ/Data_Structure/18258-큐_2-NY.py
https://www.acmicpc.net/source/37789660
이거랑 비슷한 백준 문제 풀때는 try랑 except써서 string이랑 int(push 2 할때 2)구분 했는데
유진언니가 split()으로 받고 그냥 인덱스로 접근하는 방향을 보고 저도 이번엔 그렇게 해보았습니닷
시간은 2032ms 걸렸서요.
이거 시간을 더 줄일 수 있는 방법이 있을꽈? 고수님들의 답을 기다립니다..
> [220119] NY

- BOJ/Data_Structure/18258-큐_2-GH.py
저는...
가장 앞을 가리키는 index 값을 가지는 cnt...가 리스트 여기저기 모험하는 코드입니다
킁... 데크로 풀면 편하긴 한데
몰랐다네요~!
그냥 냅다 시키는 대로... 순서대로... 순종적으로 풀엇습니다...
[1904ms] https://www.acmicpc.net/source/37817055
> [220119] GH

- BOJ/Data_Structure/18258-큐2-MH.py
아니.. 나왜 시간초과나지???? 저번에 나연언니가 readline 쓴거 보고 뽀려서도 썼는데 처음부터 계속 시간초과나서 눈물 흘렸잔아...
왜 왜... 도대체ㅇ 왤까 다들 같이 고민해줍쇼
나의 첫번째 non pass가 고작 큐라니
> [220119] MH

- Programmers/키패드_누르기-YJ.py
나름.. 노가다로 풀었어요.. 더 효과적인 풀이를 기대합니다.
> [220120] YJ

- Programmers/키패드_누르기-GH.py
와우...
키패드를 좌표로 생각하고 거리를 구했습니다...
감사합니다...
> [220120] GH

- Programmers/키패드_누르기-NY.py
키패드가 한 줄에 키가 3개씩 있으니까 그걸 이용해서 거리를 계산하면 좋을 것 같다고 생각해서
keys 라는 배열을 하나 만들어서 1부터 *, 0, #까지 저장했습니다
입력 받은 numbers를 for문으로 하나씩 돌면서
해당 숫자의 인덱스를 구해서 number_index에 저장,
왼쪽이 가지고 있던 인덱스를 L_index, 오른쪽이 가지고 있던 인덱스를 R_index로 두었습니다
절댓값 함수 abs를 사용해서
abs(해당 숫자//3 - 왼쪽인덱스//3) + abs(해당숫자%3 - 왼쪽인덱스%3) 이런식으로 왼쪽, 오른쪽 계산한 뒤
값이 작은걸 선택했습니다.
//3 을 해주면 결국 1,2,3 은 0 값. 4, 5, 6은 1값. 7, 8, 9는 2값, *, 0, #는 3값이 되어서 높이를 구할 수 있습니돻. 
0
1
2
3
이런 느낌
%3을 해주면 가로 차이를 구할 수 있습니다. 1, 2, 3이(인덱스는 0, 1, 2니까) -> 0, 1, 2 가 됩니다.
0 1 2
0 1 2
0 1 2
0 1 2
이런 느낌
그래서 각각 차를 더해서 비교했습니돻~
> [220120] NY

- Programmers/키패드_누르기-MH.py
아직 c++에서 벗어나오지 못해... 파이썬 문법 익히러가요...
주말에 더 예쁘게 코드 업데이트 해야겠어요 쩝
아 그리고 3~6줄처럼 그냥 밖에서 변수 선언하면 전역변수 아닌가여??? ㅠㅠ
왜 함수 안에서 못쓴다고 빨간줄뜨지 그래서 그냥 냅다 global 넣었어요 힝
아시는 분 가르쳐주새용..
> [220120] MH

- BOJ/Data_Structure/2164-카드2-YJ.py
https://www.acmicpc.net/source/37929454
생각해보니깐 급하게 푸느라고 주석을 못달았네요..
deque 사용했고, 맨 위에 요소 버리고, 왼쪽으로 돌리는 방식을 반복했습니다~!
> [220121] YJ

- BOJ/Data_Structure/2164-카드2-MH.py
range 범위가 헷갈려서 헤매다가 완성했어용
deque 너무 유용한 것..
> [220121] MH

- BOJ/Data_Structure/2164-카드2-GH.py
https://www.acmicpc.net/source/37967048
왕지각했습니다... 엉엉
다시는 늦지 않겠습니다.. ............ (무릎 꿇고 비는 중(
저는 저번에 못 썼던 deque 이용해서 풀었습니다
얘 정말.. 멋진 애잖아?
> [220121] GH

- Programmers/크레인_인형뽑기_게임-NY.py
흠.. 이중 for문 돌기가 싫어서 filter라는 내장 함수로 대충 찾아서 했는데
다 하고 나서 찾아보니 결국 filter 함수의 원리가 iterator라서 이중 for문에
마지막 for문까지 또 쓴 셈이 되었네용. ... (O(N^2) + O(N)).. 테러블.
쓸데없는 변수도 많고 그닥 좋은 코드는 아닌 것 같아서 오늘 내일 중으로 코드 업데이트를 한 번 더 하려구 합니다.
일단 현커밋에서의 원리는:
0이 아닌 가장 가까운 값의 인덱스를 저장해두고,(non_zeros) 해당 인덱스에 바로 접근해서 뽑기 기계로 뽑는다고 생각했습니다.
> [220122] NY

- Programmers/크레인_인형뽑기_게임-GH.py
흠냐냥.. 문제 보고
스택으로 풀면 되려나... 하고 deque 사용도 고려해 봣씁니다만
우선 그냥.. 생각한 거 그대로 짜 본 코드임니다...
근데 통과돼서 이대로 제출합니다!!! !!!!
캐릭터들이 귀엽지만 ㅍ문제 풀 맛은 안 ㄴㅏ더라고요 ^ w ^ 감사합니다..
> [220122] GH

- Programmers/크레인_인형뽑기_게임-MH.py
deque는 짱이다 아무튼 짱임
처음에 문제보고 쫄았는데 인덱스만 잘 생각하면 어렵지 않은 문제인 것 같당
점점 파이썬 range에 적응해갸는중.. 아좌자
> [220122] MH

- Sunday/Two_Sum-YJ.py
https://leetcode.com/problems/plus-one/
풀만한게 없어서 리트코드 풀었읍니다
12시 되면 그냥 머지하겠읍니다.. 안풀어도 갠찬읍니다..
> [220123] YJ

- Programmers/크레인_인형뽑기_게임-NY.py
> [220123] NY

- BOJ/Data_Structure/18258-큐_2-GH.py
저는 며칠 전에 풀었던 큐2 문제를 deque로 다시 풀어보았습니당...
deque 사랑햄... 
다들 좋은 주말이 되었기를 바랍니당 ヾ(^▽^*)))
> [220123] GH

- BOJ/Data_Structure/10866-덱-NY.py
이번 풀이는 내용이 어렵지 않으니 코드를 간단하게 적어보자! 해서 이렇게 풀었습니다(https://www.acmicpc.net/source/38028927)
시간은 100ms이 걸렸는데요,
예전에(10달전에) 풀어 둔 게 있는데 (https://www.acmicpc.net/source/26948313)
이건 리스트를 활용하고 각 명령어마다 함수를 만든 뒤 해당 입력 명령을 딕셔너리로 매칭시켜뒀는데
아마 이 부분(딕셔너리로 매칭 시키는 것)이 일일이 string 값과 비교하는 것보다 더 효율적인가봅니다. 
이때는 시간이 80ms 걸렸거든요.
코드는 길어도 시간은 예전께 더 빨랐네용
> [220124] NY

- BOJ/Data_Structure/10866-덱2-MH.py
deque 유용한 것
최대한 깔끔하게 짠다고 짰는데 칭찬해주세요 힝구
> [220124] MH

- BOJ/Data_Structure/10866-덱-YJ.py
https://www.acmicpc.net/source/38075566
여러분 그거 아시나요
deque이 비었는지 확인하는 방법
len말고도 이렇게 확인할 수 있답니다.
d가 deque 인 경우
```
if d:
else:
```
뭐 없나 찾다가 발견해서 공유해봤어요 히히
> [220124] YJ

- BOJ/Data_Structure/10866-덱-GH.py
https://www.acmicpc.net/source/38076350
84ms 나왓네용...
deque 쓰면 쓸수록.. 뽀뽀 갈기고 싶어집니다..
내가 짠 거 말고도 다양하게 할 수 있을 것 같은데.. 구경하러 가 보겠슴둥 (* ￣3)(ε￣ *)
> [220124] GH

- Programmers/없는_숫자_더하기-YJ.py
> [220125] YJ

- Programmers/없는_숫자_더하기-MH.py
- Sunday/LeetCode14-Longest_Common_Prefix-MH.py
보자마자 딱 이렇게 풀면 되겠다 해서 쉽게 풀었습니당
다른 사람 코드를 보니까 sum() 으로 간단하게 했더라구요
없는게 없는 파이썬 흠냐냥
저번 일요일에 풀었던 Leetcode - Longest Common Prefix도 같이 커밋해용
사실 이건 나연언니 풀이를 먼저 봐버려서 enumerate말고는 생각이 안났어용
하지만 꽤나.. 시간이 많이 걸린 문제...
> [220125] MH

- Programmers/없는_숫자_더하기-NY.py
저 이거 1점 밖에 못 받았어요 충격
원래 8점 9점씩 받았는데..
numbers에서 sol 배열(0부터 9까지 있음)이랑 비교해서 없는 값들만 if문으로 subtract란느 배열(차집합.. 느낌으로)에
넣어주고 마지막에 sum(subtract)으로 결과 보냈서요..
다들 몇점 받으셨어요..? 충격 실의
> [220125] NY

- Programmers/없는_숫자_더하기-GH.py
없는 걸...
추가한다... 라는 생각으로...
근데 풀이 보니까 다들 신박하고 다양하게 풀었더라고요
제 시각.. 넓어지고 있슴다... 감사함니다. 👍❤
> [220125] GH

- BOJ/Data_Structure/1874-스택_수열-MH.py
첨에 문제 이해도 안돼서 결국 블로그보고 이해한 ,,,, 
풀이도 쉽지 않았습니다.. 큰 알고리즘을 보고 코드를 짜야되는데 if문 수십개써서 모든 경우 나누다가 뒤집어 엎고 새로 짰어요..
stack에 몇번째 숫자까지 push했는지 확인해주는 변수 `stack_start`를 사용했습니다 
> 172ms   716B
> [220126] MH

- BOJ/Data_Structure/1874-스택_수열-NY.py
맨 처음에 했다가(처음 커밋) 시간이 너무 오래걸려서 어떻게 줄이면 좋을까 고민하다가
미니꺼 스윽 보니까 마지막에 print하는거를 string으로 했길래 옹! 나도 해봐야겠다 하니까
시간이 줄었는데(두 번째 커밋)
보다시피 for문 안에 while문이 있어서 O(N^2)이라 느린가 싶어서(220ms)
하나의 while문으로 바꿔봤는데(세 번째 커밋)(240ms)
오히려 더 느려저서 일단 두 개 다 추가해서 최종 커밋했습니다.
왜 하나의 while문이 시간이 더 느릴까용? 의견 부탁합니다...
시간 줄이는 팁도 부탁..
> [220126] NY

- BOJ/Data_Structure/1874-스택_수열-YJ.py
https://www.acmicpc.net/source/38188485
푸는데 1시간 걸렸어요 문제 이해부터 난관^_^...
1. 처음에 deque으로 다 감싸놨다가 필요없어서 지웠음
2. seq, stack, temp, list 이렇게 무려 4개의 list를 사용하다가 seq와 stack만 쓰는 코드로 변경 (만약 끝까지 했다면 메모리 초과 났을 듯)
- **seq**: 만들어야하는 수열
- **stack**: 만들어야하는 수열과 똑같이 만들 stack
- temp: 일단 temp에 넣고 temp[-1]하고 seq[index]랑 비교해야지~ 하고 썼다가 stack 하나로 해결 가능해서 일 한번 할거 두 번 하는 꼴이라 **삭제**
- list: 1부터 N까지 담은 list인데 for문 돌리면서 인덱스 활용할 수 있어서 **삭제**
주석 중 '넣고 봅니다'를 생각해내고 나서 비로소 삭제할 수 있었ㄷr..
> [220126] YJ

- BOJ/Data_Structure/1874-스택_수열-GH.py
와 문제 첨에는 뭔 소리야 했는데
저도... 블로그 해석본 보고 이해했습니다 ^^...
현재 값과... 타겟 값과의 관계 정리되니까... 생각보다 간단하더라고요
그치만 스택은 어려워잉...
> [220126] GH

- Programmers/음양_더하기-MH.py
첫번째껄로 일단 풀었는데 1점 나와서 띠용하고
갑자기 enumerate도 사용할 수 있을 것 같아서 풀어봤어용
> [220127] MH

- Programmers/음양_더하기.py
처음에는 enumerate로 풀고 1점 받아서
다른 사람들 풀이 아주 빠르게.. 슬쩍 봤는데 zip 이라는게 있어서 찾아봤더니
세상에 파이썬은 이런 함수도 있군요..
그래서 zip도 써봤는데 그냥 두 개의 리스트를 같이 해결할 수 있다! 이런거더라고요.
크게 다른 점은 없었는지 점수는 똑같이 1점이었습니다.
> [220127] NY

- Programmers/음양_더하기-GH.py
저는
...
바보멍청이입니다... ...
파이썬 천재가 되는 그날까지... ......
같이 공부해요...
> [220127] GH

- Programmers/음양_더하기-YJ.py
> [220127] YJ

- BOJ/Data_Structure/1935-후위_표기식2-YJ.py
https://www.acmicpc.net/source/38272941
비주얼프로그래밍의 기억을 살려..
> [220128] YJ

- BOJ/Data_Structure/1935-후위_표기식2-NY.py
음.. Syntax Error가 발생하는데 이유를 모르겠꾼뇨
런타임 에러도 아니고 틀리는것도 아니고
Syntax..Error..? 졸라 몰라서 그냥 어리둥절됨.. 힌트 주실 분.. 우울.... ㅠㅠ
> [220128] NY

- BOJ/Data_Structure/1935-후위_표기식_2-GH.py
- Programmers/내적-GH.py
ord의 쓰임도 잘 알고 갑니다...
오랜만에 스택... 후위표기식... 보네요...
휴우 다들 멋진 연휴 보내세요 ㅎㅅㅎ
> [220128] GH

- Programmers/내적-MH.py
보자마자 zip이 생각났고 뭔가 .. sum을 활용해서도 할 수 있을 것 같다고 생각(만)했어용
이걸 짧게 쓸 수 있을 것 같은데 아직 [] 안에 for문 넣어서 한 줄로 하는게 익숙하지 않아서 일단 원래 하던 방식으로 패스하고 다른 사람 코드를 봤는데 왕..
zip이랑 sum 활용하신 것 보고 감탄했어용
열심히 공부해서 꼬옥 파이썬 짱이될거야...
> [220129] MH

- Programmers/내적-NY.py
> [220129] NY

- Programmers/내적-YJ.py
> [220129] YJ

- Programmers/내적-GH.py
와악
정말 간단한 코드군요...
연휴 기념 쉬운 문제를 주셨어요 프로그래머스에서...
히힛 다들 맛있는 거 마니 드세용 🧡
> [220129] GH

- BOJ/Data_Structure/1874-스택_수열-YJ.py
https://www.acmicpc.net/source/38361742
_마자.. 나 양심업어.._
answer 받는거 리스트에서 문자열로 바꿨는데 흥미롭게도 시간은 늘고 메모리는 단축되었슴다
str에 추가하는게 list에 append 하는 것보다 오래 걸린다니... 😲
> [220130] YJ

- BOJ/Data_Structure/10828-스택-MH.py
- BOJ/Data_Structure/1158-요세푸스_문제-MH.py
- Programmers/로또의_최고_순위와_최저_순위-MH.py
친구따라 카공갔는데 할게 없어서 전에 안 풀었던 문제들 풀었어용
`로또의 최고 순위와 최저 순위`
코드 짧게 짜야된다는 생각에 이것저것 하다가 결국 오류만 나서 그냥 길게.. 차근차근 짰어요
맞춘 개수 + 순위 = 7이라는 생각을 메인으로 하면서..
꽤 시간이 많이 걸렸던 문제.. 히잉
`요세푸스 문제`
예전에 c++로 풀었을 때는 하나씩 옮기고 당기고 한다고 힘들었는데 파이썬은 rotate해서 풀 수 있을 것 같아서 이렇게 풀었어용
입력받은 k만큼 왼쪽으로 당겨서 맨 앞 원소만 계속 없애는 방식입니당
다 풀고 언니들 코드도 봤는디 유진언니랑 똑같이 풀었더라구용 희희
`스택`
그냥.. 여러번 풀어봤던 디큐나.. 큐 문제랑 비슷한 계열의 문제..
대산 이번엔 처음부터 입력을 안나누고 push in str 을 썼어용
다들 즐거운 설연휴 ~!~
> [220130] MH

- BOJ/Data_Structure/1935-후위_표기식2-NY.py
https://www.acmicpc.net/source/38365829
너무 힘든 해결이었다... 꾸엥 72ms 걸렸써요
> [220130] NY

- Programmers/로또의_최고_순위와_최저_순위_GH.py
저두 안 풀어본 문제 중
제일 흥미로운 로또 문제를 풀어보았슴니당
로또 당첨 기원 의미로다가...
최대한 간단하고... 간결하게... 짜고 싶었는데
전 만족스러워요 히힛
다들 마싯는 거 마니 드시고 계시죠 ><
> [220130] GH

- BOJ/Data_Structure/10799-쇠막대기-YJ.py
https://www.acmicpc.net/source/38391704
시간초과로 삼수한 사람 ㄴㅇㄴ
리스트에 그대로 막대기 담아둔게 풀기는 쉬웠으나 miss였던 것 같아서 sticks를 상수로 수정!
주석이랑 변수 이름 추가해서 업뎃했습니당~~
> [220131] YJ

- BOJ/Data_Structure/10799-쇠막대기-MH.py
늦어서 죄송함다.. 본가는 너무 달달해요..히잉
이 문제는 엄청..어려워보였는데 사실 알고리즘 자체는 어렵진 않더라구요...
근데 첨에 스택을 쓰는게 약간.. 사치(??) 같아서 안쓰려고 하다보니 복잡해져서 일단 써서 짜봤습니당
여는 괄호 ( 이면 스택에 push하고 닫는 괄호 ) 이면 pop한 다음 레이저인지 스틱인지 구분해줬어용
다들 비슷하게 풀지 않았을까..? 생각해봅니다
> 140ms
> [220131] MH

- Programmers/소수_만들기-MH.py
combination 이용해서 모든 조합을 가져와서 is_prime_number라는 소수인지 확인하는 함수로 짜봤어용 ~
> [220202] MH

- Programmers/소수_만들기-YJ.py
조합 활용하고 소수 판별했습니다
https://asxpyn.tistory.com/57 
예전에 블로그에 파이썬 순열이랑 조합 끄적여놓은 글입니다 총총 (별거아님주의)
https://asxpyn.tistory.com/85
이건 소수찾는 방법인 에라토스테네스의 체 설명한 글인데 제 블로그에요 근데 전 이 방법 안씀 원리는 같음
홍보하는거 아닌데 어쩌다보니 그렇게 됐다
> [220202] YJ

- Programmers/소수 만들기-NY.py
저 틀렸어요 양심고백,,
내일 다시 풀거에요,,, 졸라 거지같은 풀이,,, 거지같은 정답,,
> [220202] NY

- Programmers/소수_만들기-GH.py
저는 아리스토텔레스의 체... 를 사용해서
소수 판별했어요!! !!!!
이거 먼 개소리야... 싶겠지만
개소리 맞습니당 왈왈!
이거 말고도 소수 판별하는 법은 많아서...
다른 코드 구경하러 갑니댕
> [220202] GH

- BOJ/Data_Structure/1966-프린터_큐-NY.py
https://www.acmicpc.net/source/38520590
88ms 걸렸습니당~
덱 이용했고 M을 무조건 하나씩 빼주면서 같이 움직이다가 M 값이 0이 되면 순서 열심히 카운팅한 걸 return했습니다
함수로 구현해보았어요
> [220203] NY

- BOJ/Data_Structure/1966-프린터 큐-MH.py
que[0]가 max값보다 작으면 rotate하고, max값이면 pop해주는 방식으로 짰어요
rotate하거나 pop하고나서 궁금한 문서의 위치 M를 같이 움직여주면서 M=0이고 max값이면 return해줬어용
M 위치 같이 움직여주는게 헷갈려서 조금 걸렸슴당
> 92ms
> [220203] MH

- BOJ/Data_Structure/1966-프린터_큐-GH.py
지각 제출입니다... 제송함다... ㅜ_ㅜ
주석도 추가해서 다시 커밋하께요 시간은 96ms 나왔슴다!!
> [220203] GH

- BOJ/Data_Structure/1966-프린터_큐-YJ.py
https://www.acmicpc.net/source/38506465
중요도 리스트랑 인덱스를 담은 리스트를 따로 만들어서 구했습니다
맨 앞에 있는 요소가 가장 중요도가 높은 경우와 재배치하는 경우로 나누어서 구했어요
> [220203] YJ

- Programmers/완주하지_못한_선수-YJ.py
> [220204] YJ

- Programmers/완주하지_못한_선수-MH.py
첨에 문제보고 머야 짱쉽네 하고 둥당둥당 짰는데 안돼서 ^^,, 얕보지 말자는 생각을 하였고...
집합 set으로 하다가 Counter도 써보고 ...결국 각각 sort해서 차례대로 비교하는 방식으로 짰습니다
> [220204] MH

- Programmers/완주하지_못한_선수-GH.py
이것저것... 생각해 보다가
검색도 하다가... zip... 이라는 함수를 발견해서
같은 인덱스끼리 짝 지어주고
배열의 길이가 다를 경우 남는 인덱스는 zip 객체에서 제외되는...
고렇습니다... 감삼니다.
> [220204] GH

- BOJ/Data_Structure/2346-풍선_터뜨리기-YJ.py
https://www.acmicpc.net/source/38600421
rotate 헷갈려서 그림을 몇 번이나 그렸는지 허허 ^^
> [220205] YJ

- BOJ/Data_Structure/2346-풍선_터뜨리기-MH.py
balloon의 값과 인덱스 값을 묶고싶어서 딕셔너리를 쓰려고 했는데 또 딕셔너리 deque는 안되길래 포기하고 그냥 따로따로...
굉장히 비효율적인 코드가 탄생했습니다.. 히잉
회전하는거 너무 헷갈려서 머리 터질뻔했어요 농담입니다 사실 안터짐
> 84ms
> [220205] MH

- BOJ/Data_Structure/2346-풍선_터뜨리기-NY.py
처음에 바보같이 짜서 고생 엄청 했다는.. ㅠ..
rotate 부호 반대로 넣어서 또 엄청 헤맸네요...
시간은 100ms 걸렸어요 딕셔너리 만들어서 값 넣는다고 for문 돌리고 밑에 또 while문 돌려서 그런듯하네요
https://www.acmicpc.net/source/38619154
> [220205] NY

- BOJ/Data_Structure/2346-풍선_터뜨리기-GH.py
와악
첨에 rotate 잘못해서
읭? 햇다가 겨우겨우.. 맞혓네요..
정말 자료구조 지긋지긋하고 지겨와.. 흥 ❤
https://www.acmicpc.net/source/38631689 88ms 나왓어욤
> [220205] GH

- BOJ/Data_Structure/1966-프린터_큐-YJ.py
https://www.acmicpc.net/source/38658246
enumerate로 변경해봤는데 76ms -> 120ms로 퇴화 무슨일 ^^..허허
> [220206] YJ

- BOJ/Data_Structure/2504-괄호의_값-NY.py
와 진짜.. 이 문제 개인적으로 너무 어려웠서요 ㅜㅜ.. 다른 사람들 풀이 안보고 하려고 정말 노력했씀니다..
그것만은 알아주세요..
https://www.acmicpc.net/source/38719392
시간은 92ms 나왔는데 개인적으로 이거 깔끔한 코드는 아니라고 생각해서.. 주석 달긴  했는데 이해하기 어려울 것 같다는 생각이 들었어용
다른 좋은 풀이를 기다립니다..
추가로 참고사항: 5번 틀림 ㅋ
> [220207] NY

- BOJ/Data_Structure/2504-괄호의_값-MH.py
사실 어제 저녁부터 풀었는데 어려워...어려워서... 하...
일단 예제 정답은 나오는데 런타임 에러나서 틀렸다고 나와요... 몰라.. 일요일에 다시 풀게요
지금 간단히 설명하자면 첫번째 나오는 괄호의 짝 기준 왼쪽 오른쪽으로 나눠서 재귀함수로 풀었어요 이해안되시죠 당연함 저도 아직 이해 못 함
다음에 업데이트해서 예쁘게 가져올게요
> [220207] MH

- BOJ/Data_Structure/2504-괄호의_값-YJ.py
https://www.acmicpc.net/source/38723131
아예 검사하고 계산했는데 검사하면서 계산하는 방법도 있겠죠
> [220207] YJ

- Programmers/K번째수-MH.py
아니 이걸 한줄로 짠 멋진 사람도 있더라구요
아직 for i, j, k in commands 도 안 익숙해서 하나씩 할당하고 있던 사람 나야나
> [220208] MH

- Programmers/K번째수-NY.py
와 어제 어려운거 풀다가 이거 푸니까 살 거 같아요
그냥 한줄로 바로 슬라이싱한 배열 sorted으로 정렬된 배열 만들어주고 거기서 k번째 인덱스 뽑아서 append 해주었씁니다
> [220208] NY

- Programmers/K번째수-YJ.py
> [220208] YJ

- Programmers/K번째수- GH.py
찬양하라 프로그래머스..........................................
레벨1이라 행복해요... 숨통이 트이는 기분..
저만 백준 보이콧 하고 싶은 거 아니잔아요?ㅜ
> [220208] GH

- BOJ/Data_Structure/2800-괄호_제거-NY.py
아직.. 완료하지 못했씀니다 조금만 기다려주세요 토토토
> [220209] NY

- BOJ/Data_Structure/2800-괄호_제거-YJ.py
https://www.acmicpc.net/source/38822229
당연히 시간 초과될 줄 알았는데 신나요 ^0^
1. **괄호 쌍 인덱스** 미리 뽑아놓음
2. 조합으로 **괄호 쌍 조합** 생성
3. **괄호 쌍 조합**으로 괄호 삭제
괄호,, 이제 그만,,
> [220209] YJ

- BOJ/Data_Structure/2800-괄호_제거-MH.py
나 진짜./.. 괄호탈트왔어요 너무싫어
먼저 입력받은 수식에 하나씩 index를 부여했어요
` (2+(2*2)+2) -> [0, -100, -100, 1, -100, -100, -100, 1, -100, -100, 0]`
그 다음 combi_list는 조합하려고 만든 리스트인데
위의 예시로 들면 괄호 쌍이 총 2개니까 [0, 1]의 리스트를 만듭니다
combi는 모든 조합의 수를 저장하는 리스트이고
[0] [1], [0, 1] 의 리스트를 저장합니다
마지막으로 combi 리스트를 하나씩 가져와서
[0] 일때는 index가 0 또는 -100 (괄호 아닌 수식) 이면 temp 문자열에 더해주는 방식으로 짰습니다
> 92ms
> [220209] MH

- BOJ/Data_Structure/2800-괄호_제거-GH.py
- Programmers/모의고사-GH.py
와 레전드 졸림...
올리자마자 누울 거야...
올림ㅍㅣㄱ 쇼트트랙 보고 감동받아서 울다가 왔자나요..................
하.. 근데 괄호.. 언제쯤 안 하나요?
잘 알고 있었지만 나 괄호 너무 싫어햇네.. 그냥 치울래요....
https://www.acmicpc.net/source/38836440 72ms 나왓슴다..
페어를 이루는 괄호에 대한 index 추출함
'('를 stack.push 하다가 ')' 나올 때 stack.pop 하면 페어 이룸
모든 괄호 페어의 중복 없는 부분 집합을 구해서 괄호 제거를 함 -> combinations로
input 수식에서 부분 집합에 포함된 인덱스 위치를 인덱스 내림차순으로 정렬하고 제거함
중복 제거
그리고 나도 제거됨.. 굿나잇
> [220209] GH

- Programmers/모의고사-NY.py
> [220210] NY

- Programmers/모의고사-YJ.py
> [220210] YJ

- Programmers/2493-탑-MH.py
처음에 하나씩 검사하는 방식으로 풀었는데 시간초과나서 non-pass하고 스택으로 다시 풀었어요
stack에 아무것도 없으면 탑을 바로 넣고 있으면 비교를 시작합니당
stack의 맨 위에 있는 탑이랑 현재 탑의 길이랑 비교해서 내가 더 크면 스택에 있는 탑을 팝! 하고 마지막에 나 자신 넣어주기.... 를 반복해요
사실 시간 초과나고 멍해져서 다른 분꺼 참고했습니다 힝
> 876ms
> [220211] MH

- BOJ/Data_Structure/2493-탑-NY.py
오늘 시간 초과 때문에 너무 마음이 힘들었슴니다..
첫 시도: 재귀 -> 시간 초과
두번째 시도: 단순 비교(그리디) -> 시간 초과
세번째 시도: 
애초에 타워 값들을 저장할때 인덱스도 같이 저장, 정답 배열도 갯수만큼 미리 0 넣어두고 시작.
빈 스택을 하나 만들고, 타워 값들은 뒤에서부터 접근.
만약 스택[-1]의 값이(stack[-1][1]) towers[i][1]보다 작으면 pop하고,
towers[i][0](인덱스) + 1를 answer[stack[-1][0]] 에 저장. 
towers[i][1]보다 작은 값이 없을때까지 이 로직을 반복...!
https://www.acmicpc.net/source/38930789
시간은 912ms.. 아슬아슬
> [220211] NY

- BOJ/Data_Structure/2493-탑-YJ.py
https://www.acmicpc.net/source/38931399
쏜 신호가 오른쪽에서 왼쪽으로 계속 오고 있다고 상상을 하면서 풀었어요
신호를 모아두었다가 탑을 차례로 돌면서 해당 탑에 신호가 부딪힐 수 있으면 한번에 처리해주는 방식으로 풀었습니다
이해가 안 될 수 있어요.. 님들 탓이 아니에요.. 제 탓
> 596ms
> [220211] YJ

- BOJ/Data_Structure/2493-탑-GH.py
하아 너무 조ㅓㄹㄹㄹ라ㅏㅣㅣ다
a와 b 사이에 a보다 작은 탑이 없다는 걸 염두해 두고\
이전 탑 arr[i-1]을 확인해서 크면 result, 작다면 이전의 탑을 확인하는 방법입니다
556ms 나왓습니다
https://www.acmicpc.net/source/38943256
> [220211] GH

- Programmers/체육복-NY.py
뭐지.. 요즘 문제 한 번에 못 푸는 저주에 걸렸어요..
처음에 두 개 패스 못한 건.. 스택을 생각해서 풀었기 때문인데요.. 아예 불가능한 접근이었다는 걸 깨닫고 그냥 그리디로 바꾸었습니다.
sort해주고 중복되는 값은 remove해주고
이제 그리디로 비교해줍니다.
index값은 비교 완료된 lost값들이 중복되지 않도록 시작 index를 계속해서 업데이트 해주었습니다.
14점 받았는데 썩 좋은 코드는 아니라고 생각돼서 영 찜찜하네요
> [220212] NY

- Programmers/체육복-GH.py
흠냥..
이 문제는 '중복이 없다'와 '여벌 체육복 있는 학생도 도난당할 수 있다'가 포인트엿...다 싶어서
그것부터 냅다 처리해 주고
학생들 탐색을 시작했네요...
오른쪽부터 탐색하면 왼쪽 애가 못 받는 경우가 생ㄱㅕ서 왼쪽부터 탐색합니다
...
끝
> [220212] GH

- BOJ/Data_Structure/2800-괄호_제거-NY.py
사실 블로그의 도움을 받았습니다...
이해는 했는데요 다시 비슷한거 풀라고 하면 못 풀 듯..
나 제법 바보에요.. ㅜ.ㅜ ...
> [220213] NY

- BOJ/Data_Structure/2504-괄호의_값-MH.py
괄호 이제 그만 풀고싶어요,,,,,
저번에 재귀로 풀어서 런타임 에러났는데 결국 해결못해서 그냥 다 갈아엎고 하나씩 차근차근... 다 풀어놓고 보니 엄청 로직이 어려운건 아닌데 왤케 안풀렸는지
여는 괄호일때는 temp에 해당 값을 곱해주고 stack에 더해주고, 닫는 괄호일때는 스택 탑이랑 짝 맞는지 확인해주고 temp를 최종 값에 더해주는 방식입니다..
> [220213] MH

- BOJ/Data_Structure/2493-탑-YJ.py
블로그: https://asxpyn.tistory.com/104
소스코드: https://www.acmicpc.net/source/38931399
코드는 안바뀌었지만 블로그에 설명글 써봤어요 😎
> [220213] YJ

- BOJ/Data_Structure/2504-괄호의_값-GH.py
와우..
어제 올리는 걸 깜빡해서 급하게 올립니다..
재귀로 풀었던 거 스택으로 햇는데
너무 복잡햇고...
음... 재귀로 구현하는 게 효율적이라고 생각햇지만? 시간은 오히려 얘가 좀 더 빠르네여
https://www.acmicpc.net/source/39077904
> [220213] GH

- BOJ/Data_Structure/22942-데이터_체커-NY.py
와 이것도 하다가 눈물을..눈물을....
주석으로 달아두긴 했는데 한 번 더.. 설명하자면..
입력 받은 중심값이랑 반지름 크기로 각각 [왼쪽 x 값, 오른쪽 x값] 계산해서 요거를 sorted한 다음
조건을 충족하면 스택에 넣고 아니면 바로 no 프린트하게 해봤씀니다..
이해가 안되시면 코멘트 남겨주세용..
https://www.acmicpc.net/source/39062020
> 536ms
> [220214] NY

- BOJ/Data_Structure/22942-데이터_체커-GH.PY
처음에는... 정석으로 풀려고 했는데
런타임 에러 빠방..
그래서 찾아보니까 다들 스택으로 푸시더라고요..
이걸 어케 괄호로 풀 생각을 한 거야.... ...... ....
https://www.acmicpc.net/source/39070180 시간은 836ms 나왓어용
글고 어제 거 늦게 올려서 냅다 머지해 버려서 한 번씩.. 확인해 주시면 감사하겠습니다 ><!! ㅜㅜ
https://github.com/uujinn/Algorithm-Study/pull/127#issue-1137431061
> [220214] GH

- BOJ/Data_Structure/22942-데이터_체커-MH.py
처음엔 정석으로 풀었어요..
원의 거리를 구해서 combinations으로 모든 경우의 수를 체크를 했더니 예상과 같이 시간 초과가 나왔습니다 두둥~
사실 미리 다 풀어놨..는데 다시 푼건 일요일에 업로드할래요
여러분 풀이 뽀리러 가요
> [220214] MH

- Programmers/폰켓몬-GH.py
햐아
신나요
포켓몬은 참 귀엽더군요...
머리가 뚫리는 문제였습니다..(쉬웠다는 뜻)
보시면 바로 이해 가능하실 겁니다..
> [220215] GH

- Programmers/폰켓몬-MH.py
나름 갈금하게 잘 짰다고 생각했는데 min을 이용하는 방법이... 있었다네요
어차피 최대로 가져갈 수 있는 수는 N / 2이고 아니면 다른 종류의 수만 가져갈 수 있으니 set를 이용해서 짜봤어요~!
> [220215] MH

- BOJ/Data_Structure/1918-후위_표기식-YJ.py
- Programmers/폰켓몬-YJ.py
가장 먼저 카운터가 생각나서 이걸로 해봤어요 (〃⌒▽⌒〃)ゝ
> [220215] YJ

- Programmers/폰켓몬-NY.py
오늘 쉬워서 좀 다행이네여.. 크게 복잡하게 생각 안하고 바로 직관적으로 풀었씀니다... 총총
3점 받았씀니다...
> [220215] NY

- BOJ/Data_Structure/1918-후위_표기식-NY.py
늦제출 죄송함니더 죄송함니덩..
근데 1시부터 3시 반까지 풀었는데도 완벽하게 이해 못해서 블로그 쬐끔 참고했어요,, 울적,,
일요일에 한 번 더 풀려구요,, 
https://www.acmicpc.net/source/39209332
> 68ms
> [220217] NY

- BOJ/Data_Structure/1918-후위_표기식-MH.py
후위 표기식 몇 번이나 코딩했는데 아직도 한 번에 못 맞추는...
런타임 에러때메 조금 헤맸어요
> [220216] MH

- BOJ/Data_Structure/1918-후위_표기식-GH.py
다른 컴퓨터로 푸시를 못해 가지고..
대지각 제출 합니다...
시간은 68ms 나왓고 하나하나 비교해 주면서.. 값 저ㄴㄱ장 하는 거예요
감삼다.. 근데 스택 진자 너무 어렵다 이런 거 그만..하고싶어요
> [220216] GH

- Programmers/실패율-YJ.py
왜요?
제가 Counter 좋아하는 사람으로 보이시나요?
> [220217] YJ

- Programmers/실패율-GH.py
각 스테이지마다 for문 돌려서 실패율 구해서 result(dict)에 넣고
count를 통해 스테이지에 도달했으나 클리어 못한 플레이어의 수 구하고
result를 value 기준으로 정렬 후 keys 출력하는 방식임다
솔직히 문제가 읽을 땐 오 쉽네 이랫는데
약간... 이해가 안 돼서 좀... 빡쳣어요.
정렬하는 건 블로그 참고해써요..
> [220217] GH

- BOJ/Data_Structure/1620-나는야_포켓몬_마스터_이다솜-NY.py
이거 문제가 좀 이상해서 당황했어요
문제 자체는 별로 안 어려웠던듯...
처음에 그냥 배열로해서 index() 이런걸로 찾았는데 역시나 시간 초과 나더라구요..
딕셔너리에 양방향으로 다 저장해줬어요
키: 포켓몬 이름 - value: 숫자
키: 숫자 - value: 포켓몬 이름
이렇게 해서 그냥.. 뭐를 찾던 걍 바로 결과 나오게..!
해쉬..맵.. 아 좋다..~
https://www.acmicpc.net/source/39247591
> 312ms
> [220218] NY

- BOJ/Data_Structure/1620-나는야_포켓몬_마스터_이다솜-GH.py
given data를 dict에 key : value로  번호 : 이름, 이름 : 번호 일케 저장하고
찾아서 출력하는 방법임니다..
다솜아.. 문제가 왤케 기니? 정말.. 이 자식
중요한 거인 줄 알고 문제 열심히 읽었는데 ^^
https://www.acmicpc.net/source/39288340 320ms 걸렸네여!!
> [220218] GH

- BOJ/Data_Structure/1620-나는야_포켓몬_마스터_이다솜-MH.py
1 : 피카츄, 2 : 라이츄 .. 형식으로 저장한 dict를 피카츄 : 1, 라이츄 : 2 .. 형식으로 바꿔서 reverse_dict에 저장했어요
이렇게 하면 문제가 숫자일 때나 문자열일 때나 빠르게 정답을 가져올 수 있더라구요
물론 메모리는 ..많이 써줄게..
> [220218] MH

- Programmers/약수의 개수와 덧셈-YJ.py
다른 사람들 풀이보고 나니 효율적인 코드는 아닌 것 같아 슬퍼요 🥲
> [220219] YJ

- Programmers/약수의_개수와_덧셈-NY.py
씁.. 유진언니 말대로 다 풀고 나서 다른 사람들 풀이 보니까 개못푼듯
제곱근 생각 못하고 for문 두 번 돌려버림... 일요일에 업데이트 해야지...
작고 소중한 2점 받음 ㅋ...
> [220219] NY

- Programmers/약수의_개수와_덧셈-GH.py
약수의 개수를 먼저 구하고
약수의 개수가 짝수면 더해 주고 홀수면 빼 주는 방식으로 짯어용
근데 2점임... 쳇
> [220219] GH

- Programmers/약수의_개수와_덧셈-MH.py
으음 가볍꾼 하고 풀고 다른 사람 풀이보니까 띠용
n이 제곱수일 때 약수의 개수는 홀수... 메모메모...
> [220219] MH

- BOJ/Data_Structure/1021-회전하는_큐-GH.py
어..
새로 하나 풀어 봣습니다...
처음 큐에서의 위치를 옮겨가면서... 뽑으려는 수를 확인하고...
솔직히 문제 읽다가 지쳐서 동태눈깔로 풀엇어요
ㄴ 아진짜요?
https://www.acmicpc.net/source/39373613 72ms 나왔네용
> [220220] GH

- BOJ/Data_Structure/22942-데이터_체커-MH.py
지각제출.. 죄송합니다,,
월요일 데이터 체커 문제 시간 초과난거 다시 푼거 업데이트합니다..
원의 중심이 모두 x축 위에 있다는 점을 이용해서 원의 시작 점과 끝 점을 Circle 클래스에 넣어서 풀었어용
Circle 클래스는 원의 인덱스 no, 점의 위치 pos, 이 점의 위치가 시작인지 끝인지 is_open의 정보를 가집니당
아마 저번에 가현이가 풀었던 풀이랑.. 비슷한듯요!?
> [220220] MH

- BOJ/Data_Structure/14425-문자열집합-YJ.py
https://www.acmicpc.net/source/39385410
시간 잘못 본 줄 알고 눈 비볐네요
> 3760ms
> [220221] YJ

- BOJ/Data_Structure/14425-문자열_집합-GH.py
https://www.acmicpc.net/source/39423176 144ms 나왓어용
햐..
오랜만에 풀 만한 백준 문제였어요.. 쭈르르륵..
자료구조는 언제쯤 익숙해질까요..~ ㅜ
> [220221] GH

- BOJ/Data_Structure/14425-문자열_집합-NY.py
헤헤 쉬워서 너무너무 좋았어요 헉헉
https://www.acmicpc.net/source/39401426
> 156ms
> [220221] NY

- BOJ/Data_Structure/14425-문자열_집합-MH.py
멋진 시간...
다들 비슷하게 짰을 것 같은
> 3714ms
> [220221] MH

- Programmers/3진법_뒤집기-YJ.py
divmod 함수 쓴 풀이가 많던데 공부해봐야겠어요.. 킁
> [220222] YJ

- Programmers/3진법_뒤집기-NY.py
다 풀고 다른 사람 풀이 보니까
int(3진법 수, 3) 이렇게 그냥.. 한번에 해버리더라...
나는 직접 for문으로 돌렸는데 황망...
> [220222] NY

- Programmers/3진법_뒤집기-MH.py
divmod라는 함수가 있더라구요 그래서 슈슉슉 풀었어요
알아서 10진법으로 바꿔주는 똑똑한 int도 사용했어용
> [220222] MH

- BOJ/Data_Structure/11279-최대_힙-NY.py
저 이거 예전에도 푼 적 있는데
그때 직접 구현해서 풀었어요.. 대박이죵 ^^ [예전풀이](https://www.acmicpc.net/source/35428953)
근데 다들.. 한 번 직접 구현해보는 것도 나쁘지 않을 것 같다는 생각이...
왜냐면 시간 보면 똑같아서... 저도 기억 잘 안나서 다시 구현해보려고요...
오늘 풀때는 PriorityQueue를 사용해보았습니다
처음엔 좀 감을 못 잡아서 틀렸다가
[블로그 ](https://www.daleseo.com/python-priority-queue/)쬐끔 참고해서 감 잡았어용
블로그에서 정렬 기준을 튜플로 넣어주면 바꿀 수 있다고 해서
만약 들어온 숫자가 3이면 튜플로 (-3, 3) 이렇게 넣어줘서 앞에가 우선순위, 뒤에가 값! 이렇게 해줬습니다.
그러면 큰 숫자일수록 우선순위 값이 작아서 PriorityQueue 특징 상 작은 것부터 정렬해서 우리가 원하는대로 큰 숫자부터 정렬이 됩니다용
[오늘 제출한 코드](https://www.acmicpc.net/source/39497863)
> 436ms
> [220223] NY

- BOJ/Data_Structure/11279-최대_힙-MH.py
내장 함수에 heapq가 있더라구요.. 신기
근데 내장 heap은 최소힙밖에 안돼서 넣어줄 때 - 붙여주고 뺄 때 - 붙여줘서 이용했어용
> 172ms
> [220223] MH

- BOJ/Data_Structure/11279-최대_힙-YJ.py
https://www.acmicpc.net/source/39511845
이제 슬슬 얼레벌레 풀던 약발이 떨어져서 공부를 해야하더라구요 ㄱㅡ
공부 정리한 블로그: https://asxpyn.tistory.com/108
총총..
> 164ms
> [220223] YJ

- BOJ/Data_Structure/11279-최대_힙-GH.py
햐아..
heapq 오직 행운만 가득하길
일욜에 여유가 되면 직접 구현해 볼 예정입니다..
https://www.acmicpc.net/source/39524846  164ms 나왓삽니다
> [220223] GH

- Programmers/예산-NY.py
tmp라는 변수에 리스트의 값들을 더해주고 
그 값이 예산보다 크면 해당 인덱스를, 그 값이 같으면 인덱스 + 1을 return해주었써요
6점 받았떵 (ᐡ ɞ̴̶̷  ̫ ɞ̴̶̷ ᐡ)
> [220224] NY

- Programmers/예산-GH.py
문제 보고 두 가지 방법을 생각했어여
당연히 가장 많은 부서한테 주려면 작은 액수 신청한 부서가 우선이니까
1) 젤 작은 수부터 예산에서 빼고 예산이 마이너스가 되면 break 하기
2) 정렬하고 신청액수... 합이랑 예산 비교하기!!
그중 저는 2번으로 짰습니당 아주 짧아서 조앗어요(본심)
> [220224] GH

- Programmers/예산-MH.py
원래 sort안하고 heapq로 풀고 싶었는데 몇개 케이스가 자꾸 틀렸다고 떠서 결국 sort로 풀었어요..
보고 heapq로도 풀어보고 싶어요
> [220224] MH

- BOJ/Data_Structure/11286-절댓값_힙-MH.py
뭘써볼까 ..하다가 어제 나연언니가 쓴 PriorityQueue 생각나서 써봤어요
0이 아닌 숫자가 입력됐을 때는 절댓값을 우선순위로 push하고
0이 입력됐을 때는 0을 출력해주거나 우선순위대로 pop해줬어용
> 488ms
> [220225] MH

- BOJ/Data_Structure/11286-절대값_힙-YJ.py
https://www.acmicpc.net/source/39602610
최소 힙에 (절대값, 실제 값) 이렇게 넣어주었답니다.
> 168ms
> [220225] YJ

- BOJ/Data_Structure/11286-절댓값_힙-GH.py
기본 아이디어는 y = abs(x) 변환 시 정렬 기준이 최솟값에서 절댓값으로 바뀌는 거였습니당
튜플 이용했어요...
사실 오늘부터 C로 짜겠다고 선언햇는데
............
........
.......
하하하/
그런 거 전 못해요..
https://www.acmicpc.net/source/39626803 172ms 나왓습니다!!
> [220225] GH

- Programmers/두_개_뽑아서_더하기-MH.py
한 줄로 뚝딱 만들어 내고 싶었는데 그것 조금 어려웠고..
combination으로 2개씩 뽑아서 sum한 값을 set를 사용해서 중복 제거하고 sorted했습니다
답은 맞는데 계속 `TypeError: Object of type set is not JSON serializable` 가 떠서 뭐야...웅성웅성 했는데 알고보니 리스트[] 형태가 아닌 튜플{} 형태로 반환했더라고요
흠냐냥 6점인가... 받은 듯
> [220226] MH

- Programmers/두개_뽑아서_더하기-NY.py
combination을 써서 2개 모든 조합 구하고.. 그 조합 0번째 인덱스랑 1번째 인덱스를 더해줬써요
not in ~ 이거 쓰는것때문에 그때 리스트 쓰면 시간 복잡도가 엄청 컸던게 기억나서 처음에 set()썼고
혹시 몰라서 list써서도 테스트 해보니 이렇게 시간 차이가 나네욥 ~~
> [220226] NY

- Programmers/두_개_뽑아서_더하기-GH.py
모든 경우를 다 더해 보고 set으로 중복 제거한 후 list로 바꿔서 정렬하는 방법입니당
!!!
한 줄짜리 코드 너무나 최고 되신ㄷㅏ..........
> [220226] GH

- Sunday/220227-NY.py
직접 힙 만들고..
최대 힙 구현까지 class로 해봤써요 예전에 인터넷 강의에서 보던거 참고해서 작성했씀니다~~~!
> [220227] NY

- Sunday/append_time.py
오늘은 미니의 궁금증을 해결해보자는 핑계로 리스트 사전할당 or append 사용 시 시간 차이를 알아보았습니다^^
15번의 실험 결과 
- 사전 할당: 0.06310 - 0.07155 sec 범위
- append 사용 시: 0.07000 - 0.08023 sec 범위
시간 복잡도 자체는 O(n)으로 같은데, 사전 할당이 아주 조~금 더 빠른 느낌이었습니다
근데 저희가 코딩테스트를 풀 때는 보통 999999보다 훨씬 작은 n 값을 돌기 때문에.. 별 차이 없을 것으로 보입니다 (〃⌒▽⌒〃)ゝ 
이상입니다.
덕분에 time도 써보고 좋네요.
감사합니다.
> [220227] YJ

- Sunday/Python_class_practice-MH.py
self 어쩌고.. 신기한 파이썬 클래스 교실 ~.~
classmethod랑 staticmethod는 객체없이 사용할 수 있는 칭긔들인데 객체통해서도 접근 가능하대용 신기..
아직 둘의 차이는 자세히 모르는데 연습문제 따라 풀어봤어용
> [220227] MH

- BOJ/Data_Structure/11279-최대_힙-GH.c
와 c언어 진짜... 오랜만에 써 보는데요
머리가 딱딱하게 굳어서...
다른 분 코드 보면서 공부햏ㅅ어요........ ...
나는 걍 평생 파이썬 노예 해 주께 ㅇㅇ
https://www.acmicpc.net/source/39711590 20ms 나왓어요
역시 씨언어 ^.%
> [220227] GH

- BOJ/Data_Structure/4358-생태학-YJ.py
https://www.acmicpc.net/source/39731037
저 시간 초과 7번 걸렸어요 흑흑
cnt로 하나씩 세다가 마지막에 cnt대신 sum(c.values())로 바꿔주니깐 겨우 통과했음..
counter 믿었다구 5252
> 576ms
> [220228] YJ

- BOJ/Data_Structure/4358-생태학-NY.py
딕셔너리 쓰는건 바로 알고 로직은 쉬웠는데..
그 입력 그만 받게 되는 기준 찾는다고 생각보다 조금 오래 걸렸습니당
[스택 오버플로우](https://stackoverflow.com/questions/9573244/how-to-check-if-the-string-is-empty) 참고해서
`if not (입력받은 새 문자열): break`으로 처리해줬더니 정답이긴 했는데..
조금.. 확신이 없는 상태로 일단 제출했었답니더...
[정답 링크 ](https://www.acmicpc.net/source/39722322)
> 728ms
> [220228] NY

- BOJ/Data_Structure/4358-생태학-MH.py
시간 초과 9번 끝에 얻어낸 작고 소중한 pass^^..
다른 사람들이 올린 질문 구경하다가 미리 값을 지정할 수 있는 딕셔너리인 defaultdict가 있더라구요 신기
그래서 뽀려쓰고 EOF까지 입력받은 후 딕셔너리에 1개씩 추가해주는 방식으로 짰어용
> 608ms
> [220228] MH

- Programmers/2016년-YJ.py
이거 진짜 너무 웃기잖아ㅠ
datetime import 해서 간단하게 푼 풀이도 있더라구요! 이걸로도 함 해봐야지 ^0^
> [220301] YJ

- Programmers/2016년-MH.py
5점 받았어용
풀고 나니 month를 딕셔너리로 할 필요가 전혀 없다는 것을 깨달았네요
week는 1월 1일 기준 금요일이니까 금요일부터 써줬어요
일단 입력받은 a월 b일까지 며칠남았는지 계산한 days에서 요일을 구해줬습니댕
> [220301] MH

- Programmers/2016년-GH.py
히히 유진언니가 말한 datetime으로 후딱 풀었어용 ^^
파이썬에는 정말 없는 게 없다.. .....
다다익선........
유독 이 코드.. 다른 사람 풀이 보다가 꺽꺽 댓음..
아트코딩.. 하시는 분도 계시고 냅다 한 줄로 짜시는 숏코딩의 귀재도 계쎳음... 존경합니다
> [220301] GH

- Programmers/2016년-NY.py
standard라는 변수가 해당 월의 1일의 날짜 인덱스보다 하나 작은 값임니다
월별로 계산하고 다음에 일에 맞춰서 계산 해줬는데..
다 하고 나서 다른 사람들꺼보니까 좀 복잡하게 생각한둣..? 핳..
6점 받았는디 다른 사람들 풀이 보고 시무룩해짐 흑흑 ~
> [220301] NY

- BOJ/Data_Structure/7662-이중_우선순위_큐-YJ.py
제가 생각하고 있는 풀이 방법은
- 최소힙, 최대힙 두 개 사용 (이중)
인데, remove를 써서 그런가 계속 시간초과가 나요.. 따흐흑
counts 딕셔너리를 만들어서 따로 숫자마다 count 개수를 관리해줄까 ... 싶어서 풀다가 멈췄는데 다들 어떻게 푸시는지 ..
> [220302] YJ

- BOJ/Data_Structure/7662-이중_우선순위_큐-GH.py
- Programmers/최소직사각형-GH.py
와.. 레전드
시간 초과...............
닥터 스트레인지 해 줄게 ㅇㅇ
요리조리 찾아보니 defaultdict나.. 뭐 다양하게 풀던데 모르겟어요...............
나만 모르는 거 아니지.. ..............
심지어 검색해서 참고햇는데도 시간 초과 뜸 흥
> [220302] GH

- BOJ/Data_Structure/7662-이중_우선순위_큐-NY.py
진심.. 개강의 여파와..
계속된 시간초과로 조금 의욕을 잃어버렸어요..
직접 구현하는게 맞을까? 하는 생각도 들어요,, ㅠ.ㅠ ..
유진언니가 한 것처럼 힙 두 개(최대힙 최소힙) 만들어서도 해봤고
지금 한 것처럼 heapq definition 파일 들어가서 뒤지다가 _heapfiy_max라는걸로 최대힙도 만들어봤는데
그냥 다 시간 초과...
heapify가 O(logN)일텐데.... 왜.. 안되는건지 잘 모르겠고...
직접 구현해야 하나.. 직접.. 구현... 그런 생각이..
최대최소힙이라는게 따로 있는 것 같던데... 퀭
> [220302] NY

- BOJ/Data_Structure/7662-이중_우선순위_큐-MH.py
난 이제.. 지쳤어요.. 떙벌땡벌
힙을 이용해서 최소값 최대값 제거했는데 nlargest랑 index를 같이 써서 그런가 시간초과가 자꾸 나네요....
그냥.. 일요일에 다시 풀어도 될까요..
다른 분들의 풀이.. 궁금 궁금..
> [220302] MH

- Programmers/최소직사각형-YJ.py
이걸 힙으로 푼 사람들도 있던데 .. 난 언제쯤 >>응용<<이라는걸 생각할 수 있을까 ㅎ?
https://asxpyn.tistory.com/56
> [220303] YJ

- Programmers/2075-N번째_큰_수.py
- Programmers/최소직사각형-MH.py
내 작고 소중한 3점....
다른 사람 풀이 무슨.. 뭘 적은지도 모르겠어요 해석해주실분,,~
> [220303] MH

- Programmers/최소직사각형-GH.py
햐아~
백준 풀다가 프로그래머스 보면 천사 같은 기분
저는 비교해서 리스트에 작은 값, 큰 값 순서로 되게 정렬해 줬어용
그리고 거기서 max를 구해서 곱하는 방법임다
근데 2점 받음 ㅋ
> [220303] GH

- Programmers/최소_직사각형-NY.py
오늘.. 제가 극한의 스케줄과 스트레스로 인해 집중 못해서..
빨리 못 풀었서요 ㅜㅜ 대충 생각한 방법은 그리디로 비교하면서 max값 바꿔주는건데
내일 새벽에 고치려구요
> [220303] NY

- BOJ/Data_Structure/2075-N번째_큰_수-NY.py
처음에 당연히 힙에 N * N 다 넣었다가 메모리 초과 먹구..
질문 게시판 슬쩍 보다가 N개로 제한해보라는 힌트를 보고 후다닥 고쳤어요...
메모리 초과는 어떻게 해결해야 좋을지 몰라 막막한 마음에 좀 너무 일찍 질문 게시판을 본 것 같긴 한뎋..
그래도 해결했다는 것에 의의를.. ^^..
https://www.acmicpc.net/source/39946986
> 1032ms
> [220304] NY

- BOJ/Data_Structure/2075-N번째_큰_수-GH.py
하~ ㅜㅜ
딱 봐도 복잡.. 시간 초과 날 것 같은 예감이 들어서
어떻게 input을 받아서 처리할지 고민을 많이 햇습니다...
input으로 N을 받고 heap이라는 배열에 값을 넣어용
min-heap을 사용해서... 우선순위 큐의 길이를 N만큼 유지합니다..
검색 살짝.. 했지만...
막상 코드 보니 그닥 복잡하지도 ㅇㅏㄶ은데 알고리즘을 떠올리기에는
어려웟다...입니다
https://www.acmicpc.net/source/39952478 872ms 나왓슴니다!!!!!!!!!!!!
> [220304] GH

- Programmers/나머지가_1이_되는_수_찾기-YJ.py
작은 수부터 계속 나눠서 할까하다가 괜히 복잡하게 풀어봤습니다 (〃⌒▽⌒〃)ゝ 
괜히 한거 맞는듯 ^^
짝수/홀수 나누고, 홀수 안에서도 소수/소수 아닌 수 나누어서 해결했습니다
> [220305] YJ

- Programmers/나머지가_1이_되는_수_찾기-NY.py
오늘꺼 쉬워서 너무너무 좋아요 행복해요~~~
저 그냥 단순하게 생각해서 3점 받았는데 더 멋진 풀이 기대합니다
> [220305] NY

- Programmers/나머지가_1이_되는_수_찾기-MH.py
산뜻한 주말 문제네요 ㅎㅅㅎ
한줄로 하려고 []안에 넣었더니 리스트로 반환하길래 그냥 뒤에 [0] 붙여서 값만 빼냈어요
람다식으로 짠 사람 풀이도 보고싶네용
2점받음 꾸엥
> [220305] MH

- Programmers/나머지가_1이_되는_수_찿기-GH.py
3점을 받고 말앗따,..
질문에 대한 답변ㅇ은
일욜에 남기도록 하겟슴다!!!!!!
못 ㅁ푼 문제도 오늘 풀게요 감사합지ㅏ당!
> [220305] GH

- BOJ/Data_Structure/7662-이중_우선순위_큐-NY.py
하.. 진짜 개빡.. 처음에는 딕셔너리 썼다가..
그다음엔 이 로직이 잘못됐나 싶어서 numbers라는 리스트를 만들어서 썼는데..
그것마저 내 뜻대로 안돼서 걍 정답이 안 나오는데 너무 지쳐서 일단 한 번 업로드 합니다...
내일 오전에 또 다시 해보려고... 하 ㅜ..
피드백 안해주셔도 된다는... 그냥 approve 체크만 해주세요.. ㅠ..
> [220306] NY

- BOJ/Data_Structure/1302-베스트셀러-MH.py
죄송..죄송함다 이중 어쩌고 풀기 너무 싫어서 자료구조 문제 중에 체크 안된거 하나 풀었어요
Counter 이용하는 쉬운 문제였구요
정렬하는데 제일 공들였어요
그나저나 tuple의 key만 출력을 어떻게 하지 하다가 그냥 [0]붙였는데 돼서 신기했어요
http://boj.kr/9a4039f5b39f4033bb0cc6bb2fdadd8a
> [220306] MH

- BOJ/Data_Structure/7662-이중_우선순위_큐-YJ.py
흑흑 정말 어렵다
count라는 딕셔너리 따로 만들어서, 최대 힙 최소 힙에 넣고 뺄때마다 개수 관리해줬어요
이 방법은 이미 삭제해서 없어진 숫자가 있기때문에 최대힙/최소힙의 딕셔너리 개수에 유의하면서 풀어야하더라구요.. 머리아파서 죽었습니다
최종적으로 counts value가 0보다 큰 수 중에 max 숫자와 min 숫자가 정답입니다.
말로하기 어렵네요.. 블로그 갈겨올게요
> [220306] YJ

- BOJ/Data_Structure/7662-이중_우선순위_큐-GH.py
이중 우선순위 큐?
진짜 모르겟다...
짜다짜다 안 돼서 눈물을 짯고...
저는 검색해 가지구 코드 보고 알고리즘 이해하는 쪽으로
오늘은 그렇게 공부했어여...
만간 직접 제가... 완성해 보겟습니다....... ㅜㅅㅜ
> [220306] GH

- BOJ/Data_Structure/21939-문제_추천_시스템_Version_1-YJ.py
- BOJ/Data_Structure/7662-이중_우선순위_큐-YJ.py
ㅠㅠ .. 음 문제가득코드.... print문 출력도 안됨 우하하 .. 
내일 다시 고쳐보겠습니다
> [220307] YJ

- BOJ/Data_Structure/21939-문제_추천_시스템_Version_1-MH.py
- BOJ/Data_Structure/7662-이중_우선순위_큐-MH.py
예시도 반례도 다 맞는데 왜 틀린걸까.....
흠녀녕.... 이유라도 알려조라....
> [220307] MH

- BOJ/Data_Structure/21939-문제_추천_시스템_Version_1-GH.py
조건을 정확히 어떻게 해야 할지 생각은 햇는데
안 떠올라서 그냥..
포기햇어요 더 이상은 도저히 머리가 안 돌아가서.. ..
패스해 올게요..
command를 사실 따로 빼고 싶은데 그렇게 했을 때 어떻게 또 다룰지는 고민이 돼서
... 여러 방향을 생각해 보고 다른 것들도 참고하면서
완성해오겟습다 8ㅅ8!!
> [220307] GH

- BOJ/Data_Structure/21939-문제_추천_시스템_Version_1-NY.py
반례 해결을 아직 못해서용...
내일 오전에 업데이트 해보겠써요 아자아자
> [220307] NY

- Programmers/부족한_금액_계산하기-YJ.py
> [220308] YJ

- BOJ/Data_Structure/21939-문제_추천_시스템_Version_1-MH.py
- Programmers/부족한_금액_계산하기-MH.py
8점..꽤나 높은 점수나와서 놀랐어요
가지고 있는 money에서 써야하는 돈 빼서 return 해줬슴다
> [220308] MH

- Programmers/부족한_금액_계산하기-NY.py
어제꺼 수정하다가 프로그래머스 푼 거 이제 올려용... (ᐡ ɞ̴̶̷  ̫ ɞ̴̶̷ ᐡ) 
9점 예엨
> [220308] NY

- BOJ/Data_Structure/21939-문제_추천_시스템_Version_1-NY.py
안녕하세요 바보입니다..
출력할때 max 앞에 마이너스 기호를 안 붙여줘서 틀렸던거였습니다
진짜 바보 등장~ 바보.,.~ 바보~
저는 저번 문제랑 똑같은 로직인데 그냥 어떤 선택지가 들어오던.. 걍 함수로 heappop이라는걸 만들어서
누락되는 문제 없도록 안전하게 모든 반복문에서 무조건 돌아가게 했어요...
https://www.acmicpc.net/source/40179183
> 292ms
> [220309] NY

- BOJ/Data_Structure/21939-문제_추천_시스템_Version_1-YJ.py
- BOJ/Data_Structure/21939-문제_추천_시스템_Version_2-YJ.py
https://www.acmicpc.net/source/40167051
우선 이전 문제 풀었어요!!
힙에 넣어줄 때 최대 힙에 경우 원래 난이도만 음수로 집어넣었는데, 문제 번호까지 집어넣었습니다. 
그리고 이미 푼 문제들 정리해주는건 recommend랑 add에 둘 다 넣어줬습니다~!
오늘 문제 풀러 갑니다요
> [220309] YJ

- Programmers/부족한_금액_계산하기-GH.py
for문으로 1~count까지 price 곱한 금액을 총 비용으로 할당하고
예산 money보다 total 금액이 작으면 money에서 total을 뺀 값을 return
가지고 있는 것보다 total이 더 크면 0을 return
합
니
다
!!!
아차 저는 8점?? 받았어요
> [220308] GH

- Programmers/[1차]_비밀지도-MH.py
2점 짝고소중해요
bin으로 비트연산해주니까 앞에 '0b'붙어서 슬라이싱해주고
replace로 바꾸고 각 문자열 길이 n으로 맞춰주고 ~,,,
> [220310] MH

- Programmers/1차_비밀지도-NY.py
저 이거 그냥 str으로 했는데
다른 사람들 풀이 보니까 비트 연산자 쓰더라고요.... 
근데 생각해보니까 비트 연산자 쓰는게 맞는듯........ 
2점 밖에 못 받았슴니다,, 오늘 오후에 비트 연산자 공부 좀 더 해서 새로 업데이트 해볼게요
> [220310] NY

- Programmers/1차_비밀지도-GH.py
저는...
지도 두 개를 이진수로 변환해서 합친 후 변환하는 순서로... 생각했구요
bin(arr1[i] | arr2[i]) 각각 지도를 이진수로 변환해 줬구용 두 지도 모두 0일 때 공백이므로 or로 계산했어여
.zfill(n)은 이진수 n자리 숫자가 아니면 n이 될 때까지 0을 추가하는 함수라고 함니다
역시 파이썬.. 없는 게 없다. 그치만 2점 받앗어요 ㅠ
> [220310] GH

- BOJ/Data_Structure/2696-중앙값_구하기-MH.py
내가 생각해도 이해못할 .... 난잡 그자체 코드
다른 분들의 기깔나는 풀이 기대합니다..
> 2604ms
> [220311] MH

- BOJ/Data_Structure/2696-중앙값_구하기-YJ.py
한시간동안 머리 싸매는중..
왼쪽힙 오른쪽힙 각각 최대힙 최소힙으로 만들어서 크기 비교하는건 생각했는데 어.. 막막..
> [220311] YJ

- BOJ/Data_Structure/2696_중앙값_구하기-GH.py
더 멋진 코드로...
꼬옥 찾아올 거야.........
> [220311] GH

- Programmers/가운데_글자_가져오기-NY.py
나름 한 줄 코딩 했다고 생각했는데
다른 사람 풀이 1위 풀이보고 약간 자신감 하락함 머쓱
> [220312] NY

- Programmers/가운데_글자_가져오기-YJ.py
> [220312] YJ

- Programmers/가운데_글자_가져오기-MH.py
작고 소중한 1점... 받았어요
뭔가 기깔난 로직을 짜고 싶었지만 흑흑
> [220312] MH

- Programmers/가운데_글자_가져오기-GH.py
대박.. 소중ㅎ란 1점 받았어요........
홀짝 이용햇는데... 이걸로 부족하니..ㅣ.?
> [220312] GH

- BOJ/Data_Structure/2696_중앙값_구하기-GH.py
어억..
넘 모르겠어서 ㅜㅜ 검색해 보면서 했어요
난 정마.ㄹ.. 자료구조... 어려워.. 으엉엉
런타임 에러인데 아마 변수명이나.. 그런 문제일 것 같아요 다시 수정해야겠어요
> [220313] GH

- BOJ/Data_Structure/21942-부품_대여장-YJ.py
다 풀고 자고 싶었는데 내일 다시 상쾌하게 풀어보려구요
Test Case 1은 되는데 아마 다른 부분이 안되나봐요 
내가 뭘 놓쳤겠지 뭐..
> [220315] YJ

- BOJ/Data_Structure/21942-부품_대여장-NY.py
수정 완료했습니당.
민희가 알려준대로 같은 사람이 다시 같은 물건을 빌린 경우를 고려를 안했더군요!!
그리고 마지막에 정렬할때 lambda 썼는데 바보같이 기준을 M으로 두고 하고 있었다는 걸 마지막에 되어서야 알았슴니당...
아마 테스트 케이스가 너무 적어서 그렇게 해도 결과가 잘 나온 거 같네용..
https://www.acmicpc.net/source/40441842
> 1208ms
> [220314] NY

- BOJ/Data_Structure/21942-부품_대여장-GH.py
처음에 생각한 대로 풀었다가 장렬히 실패해서
다시 엎었다가 시작했는데...
중간중간 다른 사람 코드 참고했더니 그것밖에 안 떠올라서
후레쉬하게 다시 풀 거예요...
실력이 점점 늘어야 하는데 떨어지는 듯.. 힝냐
> [220314] GH

- Programmers/[1차]_다트_게임-MH.py
풀면서 배우는 정규식..
re.compile에서 () 괄호가 묶어주는 역할이더라구요..
5점 받았습니댕
> [220315] MH

- Programmers/[1차]_다트_게임-GH.py
와.. compile이라는 내장 함수 첨 알았거든요... ...
좀 머찐 친구일지도... ...
대박.. 6점 받앗어용
https://nan491.tistory.com/entry/Python-3-compile-%ED%95%A8%EC%88%98
https://homzzang.com/b/py-104
compile 관련 블로그... 참고참고...
> [220315] GH

- BOJ/Tree/11725-트리의_부모_찾기-NY.py
아침에 해보고 이해가 안돼서 유튜브도 보고.. 블로그도 여러개 봤다는....
이게 그래프인데... 트리.. ? 인.. 그런 상황인거같더라고용..
이해는 했는데 비슷한거 다시 풀라고 하면 한 번에 못 풀 것 같은 그런 문제네요.... 
주석은 달았는데 이해가 될련지
https://www.acmicpc.net/source/40521851
> 376ms
> [220316] NY

- BOJ/Tree/11725-트리의_부모_찾기-MH.py
tree 너무 오랜만에 봐서 다 까먹었어요... 따로 공부해야 할 듯
코드 공부하면서 풀었습니다 히잉힝힝..........
http://boj.kr/bf52a6a85ad942969584e3746dc5ed0a
> 392ms
> [220316] MH

- BOJ/Data_Structure/11725_트리의_부모_찾기-GH.py
DFS로 풀엇어요...
트리 진짜 다 까먹어서 트리 그리는 것부터 다시 고민해 봄 ;;; ;;;;
이게 맛나....
그치 이러려고 공부하는 거지...
717329329b14ba0c19733731698526b5effbd5b7 < 런타임에러 떳어요...
Pass라ㅣ고 커밋한 애도 틀린 애입ㄴㅣ다... ㅜㅅㅡ
머... 전 할 수 있습니다. 킁냐
> [220316] GH

- Programmers/같은_숫자는_싫어-NY.py
5점 받았서용..~ 효율성 테스트라는 것도 있던데
효율성 테스트가 빠르고 메모리가 적으면 더 높은 점수가 나오는 구조인지...?.?
더 높은 점수 받으신 분들 알려주세여~ 다른 사람들 풀이 보니까 슬라이싱 많이 쓰던데 그러면 훨씬 더 빠르려나요
> [220317] NY

- Programmers/같은_숫자는_싫어-MH.py
> [220317] MH

- Programmers/같은_숫자는_싫어-YJ.py
> [220317] YJ

- Programmers/같은_숫자는_싫어-GH.py
도대체 같은 숫자가 왜 싫은 거니..
받아들여.......
4점...받았어용
> [220317] GH

- BOJ/Tree/1991-트리_순회-MH.py
하..... 트리를 거의 한달간 마주쳐야 한다는 생각하니 아찔해요
전위 : root 왼 오
중위 : 왼 root 오
후위 : 왼 오 root
메모메모....
그리고 다른 사람들 풀이보니까 저랑 비슷한데 72ms 나오고.. 막 그러던데
제가 아마 튜플을 딕셔너리에 집어넣어서 그런 것 같아요 흠녕
어쩔튜플
http://boj.kr/590028c11ced4451975a6e16ba53ab6f
> 208ms
> [220318] MH

- BOJ/Tree/1991-트리_순회-YJ.py
https://www.acmicpc.net/source/40655049
딕셔너리에 넣어서 그래프 느낌으로 풀어줬어요 쉽게 풀었는데 졸음이 와서 자꾸 쓸데없이 틀렸다는 엣쿵
테스트 케이스 넣어보면 이렇습니다 
```python
{'A': ['B', 'C'], 'B': ['D', '.'], 'C': ['E', 'F'], 'E': ['.', '.'], 'F': ['.', 'G'], 'D': ['.', '.'], 'G': ['.', '.']}
```
> 72ms
> [220319] YJ

- BOJ/Tree/1991-트리_순회-NY.py
저는 Node라는 class를 따로 만들어서 해결했습니당
node끼리의 연결성을 위해서 tree라는 알파벳 갯수에 맞는 배열을 만들어두고
ascii 코드로 변환해서 해당 인덱스에 맞는 값들을 넣어줘서 계속 연속적으로 호출될수있게 했어요
https://www.acmicpc.net/source/40660645
> 68ms
> [220319] NY

- BOJ/Data_Structure/1991-트리_순회-GH.py
진짜.. 트리를.. 한 달 동안 마주해야 한다는 게 실화..예요?
거거거거 거짓말...... ..
트리 순회만 한 달 해 주께 ㅇㅇ
> https://www.acmicpc.net/source/40656397
> 68ms
> [220318] GH

- Programmers/나누어_떨어지는_숫자_배열-MH.py
대박 다른 사람 풀이보는데 이때까지 값이 있으면
`sorted(answer) if answer else [-1]`
이렇게 썼는데
`sorted(answer) or [-1]`
위처럼 쓸 수 있다는 사실도 알았어요
앞에 값이 없으면 뒤의 값을 반환하나봐요 신기..
> [220319] MH

- Programmers/나누어_떨어지는_숫자_배열-GH.py
> [220319] GH

- BOJ/Tree/9372-상근이의_여행-MH.py
추천문제 아닌 것 중에 트리 골라서 풀었어용
deque를 활용한 BFS를 했는데 연결된 모든 노드가 들어있는 tree에서 1번 노드부터 연결된 노드 하나씩 보면서 방문했는지 체크해줬습니당
근데 사실 이 문제 보시면 아시겠지만 모든 비행기가 연결되어 있어서 걍 N - 1 프린트 하면 답이긴해요 하핫
http://boj.kr/ab1f3bea87bf48a5b6787f4b2467fac5
> 284ms
> [220320] MH

- BOJ/Data_Structure/21942-부품_대여장-YJ.py
datetime을 이용해서 풀었구요 dict 안에 dict 넣었습니당!!
이전 풀이에서 보충해서 풀이 완료
> [220320] YJ

- BOJ/Tree/9934-완전_이진_트리-NY.py
정답률 높아서 금방 풀 줄 알았는데 ... 아니여따..
처음에 limit 안 늘려줘서 런타임 에러가 두 번이나 났네욤...
재귀로 풀었습니당
https://www.acmicpc.net/source/40746948
> 72ms
> [220321] NY

- BOJ/Data_Structure/11725_트리의_부모_찾기-GH.py
- BOJ/Data_Structure/21942-부품_대여장-GH.py
> bac972fd1f4139f9acc8e6477f7b6c50f91400d6
얘는... limit를 10 ** 6으로 바꿔 주니까 됏고요!!!
> 55fc6e25a021c9b339c5a3bd56644e27714b585c
얘는.. 도저히 생각이 안 나서.. 이코드보면서
고민해봣어요 글고 유진언니 코드도 보면서
뽀릴라고요(공부하겟다는뜻)
분석 좀 더 해 보께요..
> [220320] GH

- BOJ/Tree/9934-완전_이진_트리-MH.py
트리.. 나에게 너무 어려운 것
재귀로 이진 트리 만들었는데 재귀 과정에서 결과가 되는 tree랑 입력받은 seq 헷갈려서 좀 헤맸어요
http://boj.kr/17688fe03e6f449c96b619b01b2ece91
> 76ms
> [220321] MH

- BOJ/Data_Structure/9934-완전_이진_트리-YJ.py
> [220321] YJ

- BOJ/Data_Structure/9934-완전_이진_트리-GH.py
이게.. 무 무슨 말이고... 까지는 됐는데
날 시원하게 해결해ㅑ 주는 코드가 없어서 이걸로...
공부햇다는 전설 아닌 레전드...
이번 달 끝날 땐... 나도 트리 천재...?!
> [220321] GH

- Programmers/두_정수_사이의_합-NY.py
이거 처음에는. .. 고딩때 쓰던 등차 수열의 합 n*(n+1)//2 이거 알죵 이거 쓰려고 했는데
마이너스 여부에 따라 포함관계가 달라지고 한 번 꼬이니까 생각이 깔끔하게 안돼서 sum썼는데
시간이 너무 오래 걸려서.... 주말에 한 번 더 제대로 구현해서 비교해보는게 목표
> [220322] NY

- Programmers/두_정수_사이의_합-YJ.py
> [220322] YJ

- Programmers/두_정수_사이의_합-MH.py
간단한 문제여서 더 멋지게 푸려고 했는데 다른 사람 풀이보니까 워웅엉..
2점받은 이유를 알겠어요.... 시무룩
> [220322] MH

- Programmers/두_정수_사이의_합-GH.py
꼬옥... 2점 받아주면 돼... ㅜ
사랑스러운 한 줄 코드 바칩니다...
> [220322] GH

- BOJ/Tree/1068-트리-NY.py
2시간 넘게 잡고 있었는데 로직 구현에서 자꾸만 허점이 생겨서..
너무 답답해서 걍 블로그 보면서 구현했는데
사실 완벽하게 이해를 못했어요
ㅜ... 일요일에 다시 할거야.. 뿌엑
> [220323] NY

- Programmers/1068-트리-MH.py
문제가 뭐라는건지 .... 첨에 인덱스로 하는건가 값으로 하는건가 이해못하고 헤매다가 블로그 참고해서 구현했는데 너무 배고파서 그냥 일요일에 제대로 공부하고 다시 풀래여...
트리부셔버릴거임
> [220323] MH

- BOJ/Tree/1068-트리-YJ.py
https://www.acmicpc.net/source/40872674
remove 써서 시간초과 날까봐 숨참음 헉헉
> 68ms
> [220323] YJ

- BOJ/Data_Structure/1068-트리-GH.py
트리야...
내가 바보라서 미안...
DFS로 탐색해 줄게...
> https://www.acmicpc.net/source/40881186
> 68ms
> [220323] GH

- Programmers/문자열_내_마음대로_정렬하기-NY.py
첨에 이해 못해서 헤맸어요..
1. 첫 커밋: n번째 문자 뽑아서 새로운 2차원 배열에다가 ["car": "a"] 이런식으로 넣어두고 1번쨰 인덱스 값을 기준으로 정렬했어요
2.두 번째 커밋: 생각해보니까.. n번째로도 할 수 있을 것 같아서 sorted된 거를 한 번 더 n기준으로 sorted해서 넘겼습니다
점수는 똑같았었어요~!.!
> [220324] NY

- Programmers/문자열_내_맘대로_정렬하기-YJ.py
> [220324] YJ

- Programmers/문자열_내_마음대로_정렬하기-GH.py
이얏호
갓로그래머스!
전 5점 받앗어요
다들 비섯비섯한데 외... 점수 차이가 나지요?
> [220324] GH

- Programmers/5639-이진_검색_트리-MH.py
재귀로 print하면서 순회하는는 방식은 이해가 너무 어려워서 아예 배열 자체를 후위순회 순서로 재배열했어요
0번째부터 root로 놓고 root보다 큰 수의 인덱스 기준으로 왼쪽 가지 오른쪽 가지 나눠서 재배열했습니당
http://boj.kr/c6394080252b4086931819f8f9ce9101
> 4780ms
> [220325] MH

- BOJ/Data_Structure/5639-이진_검색_트리-GH.py
루트 값을 기준으로
루트보다 큰 값이 존재하면 그 값을 기준으로 왼쪽, 오른쪽 트리 나눠 주고
재귀를 통해 계속 반복하면
왼쪽 서브트리 - 오른쪽 서브트리 - 루트 < 요 순서로 프린트되는 방식..? 입니다.. 킁
> https://www.acmicpc.net/source/41001108
> 4160ms
> [220325] GH

- BOJ/Tree/5639-이진_검색_트리-NY.py
어제꺼 황급히 올리기..
일단 생각한 로직은 
해당 노드와 연결된 왼쪽 자식 노드와 오른쪽 자식 노드를 배열에 저장하고,
해당 노드의 부모 노드도 따로 하나 저장하는 배열을 만들어서 입력값을 스택처럼 취급해서 하나 들어오면 그거에 대한 처리를 해준ㅂ니덩.
그런 다음에 후위 순회를 한다고 생각했서요
늦어서 죄송함니덩 ( ´•̥ω•̥` ) .. 아빠 생일이라서 늦게 생각하고 커밋하여서.. 풀리퀘 안하고 드르렁 자버림 ㅠ.ㅠ
> [220325] NY

- BOJ/Tree/5639-이진_검색_트리-YJ.py
> [220325] YJ

- Programmers/문자열_내_p와_y의_개수-YJ.py
> [220327] YJ

- Programmers/문자열_내_p와_y의_개수-NY.py
다 풀고 다른 사람 풀이보고 힝.. 함..
저렇게 풀 수가 있꾸나.. 시무룩.. 바보갓은나애모습
> [220326] NY

- Programmers/문자열_내_p와_y의_개수-MH.py
가볍게 3점....
다른 사람 풀이 맨 위에 있는거랑 같아서 얏호 했는데 보니까 if 구문 넣을 필요도 없었다네요
> [220326] MH

- BOJ/Tree/5639-이진_검색_트리-NY.py
도저히 스스로 못 풀어서 남의 코드 보면서 대충 끼워맞췄ㄴ느데..
만족스럽지가 않네요.. ㅠ.. 다음주에 다시 해야지... 퀭..
> [220327] NY

- Programmers/문자열_내_p와_y의_개수-GH.py
왁..
짝고 소중한 2점...... .............
> [220326] GH

- BOJ/Data_Structure/9372-상근이의_여행-GH.py
히힛..
어제 갑자기 잠들어서..
대지각 제출합니다. 후엥엥 지각비 내러갑니다..
지난주 일요일에 미니가 푼 문제예용
문제 이름이 귀여워서 뽀렷어요..
그때 미니가 말한 것처럼 n-1... 하ㅏ면 돼서 생각보다 간단해써요
> https://www.acmicpc.net/source/41100399
> 192 ms
> [220327] GH

- BOJ/Tree/6416-트리인가?-NY.py
채점 결과를 몰라요.. 어리둥절..
최선을 다해보았는데.. 지금 내 로직이 틀린건지 Input을 잘못 받은건지 그걸 잘 모르겠어서 ㅜㅜㅜ
> [220328] NY

- BOJ/Tree/6416-트리인가-MH.py
입력받고 이어진 간선들 list로 만드는 것 까지 했는데
tree인지 판별하는건... 아직 생각 중입니다..
흠녀녕 일요일에 봐 트리야.....
> [220328] MH

- BOJ/Data_Structure/6416-트리인가-GH.c
냅다 c로 짜는 여성 어때요..
사실 c로 과제 하고 잇엇거든요...
이 코드가.. 맞긴 햇지만... 다른 코드 보면서 구조 익힌 거라서
이 알고리즘 참고해서...
파이썬으로 짜 보려고요...
그럼... 시간 초과 나겟지...?
> [220328] GH

- Programmers/문자열_내림차순으로_배치하기-NY.py
프로그래머스 너무 좋당
한줄 풀이를 가능하게 하는 프로그래머스 너는 짱이야..~
> [220329] NY

- Programmers/문자열_내림차순으로_배치하기.py
> [220329] YJ

- Programmers/문자열_내림차순으로_배치하기-GH.py
작고 소중한 3점...
다들 비슷하게 풀었을 거라 생각되어요...
> [220329] GH

- BOJ/Tree/14675-단절점과_단절선-YJ.py
https://www.acmicpc.net/source/41231831
우와우와우와
> [220330] YJ

- BOJ/Tree/14675-단절점과_단절선-NY.py
내가 봤을때 이문제.. 뭔가 절단선 조건이 잘못된 거 아닌가..
애초에 절단선에 대해서 물어보는게 뭔 의미가 있나 싶었어요.. 그리고 예상한대로 딱히 뭔가 안해줘도 절단선은 그냥 맞았다는...
황당... 난이도 측정이 과하게 된 것 같아요
오늘 문제 이지이지..
https://www.acmicpc.net/source/41195381
> 320ms
> [220330] NY

- BOJ/Tree/14675-단절점과_단절선-MH.py
이게.. 트리 문제인가?
근데 첨에 문제 이해 못해서 어?? 어? 이러고 있었음
백준은 항상 입력받는게 잘 이해가 안되는.. 내가 문제겟찌
http://boj.kr/77f328b43203450a8d6e4ab8089870a2
> 332ms
> [220330] MH

- Programmers/문자열_다루기_기본-NY.py
진짜 코테에 이런 문제만 나왔으면 좋겠덩 히히 ㅈㅅㅎㄴㄷ
> [220331] NY

- BOJ/Data_Structure/14675-단절점과_단절선-GH.py
모든.. 간선은.... 단절선..인데 왜 구해요
흥
다들 비섯하게 풀엇네요 오예
> https://www.acmicpc.net/source/41243668
> 324ms
> [220330] GH

- Programmers/문자열_다루기_기본-MH.py
> [220331] MH

- Programmers/문자열_다루기_기본-YJ.py
잊지말자 조건 자체로 True False 반환하기~~~
그래도 오랜만에 7점 ^^..
> [220331] YJ

- Programmers/문자열_다루기_기본-GH.py
> [220331] GH

- BOJ/Tree/17073-나무_위의_빗물-YJ.py
트리 가장 아래에 있는 노드들 개수 구해서 풀었습니다
https://www.acmicpc.net/source/41346816
> [220401] YJ

- BOJ/Tree/17073-나무_위의_빗물-MH.py
벌써 4월이에용 대박
처음에 이걸 각 노드별로 확률을 계산해야 하나 했는데 종이에 트리 한번 그려보니까 결국 모든 물은 leaf에 존재하더라구요
어차피 평균 구하는거니까 leaf에 있는 모든 물 더하면 W 이고 그럼 leaf 개수만 구하면 되겠다고 이해했어요!
http://boj.kr/48339a5b54e847589196bff5c797c83d
> 1300ms
> [220401] MH

- BOJ/Tree/17073-나무_위의_빗물-NY.py
처음에 기댓값이라는 정의가 너무 아리까리해서.. 고민을 되게 많이했어요 ㅜㅜ
그리구 사실 이해가 잘 안돼서 질문 게시판 보고 해결했는데
결국 결과론적으로 때려맞추기식으로 이해했는데...
기댓값을 막 공식으로 써서 분모 분자에 이게 이렇게 들어가는게 이게 날아가서
결국 W / leaf 개수다! 이 과정을 이해를 못했어요 다른 사람들 블로그도 다 대충 써놔서...
이거 이해하신분..?
기댓값의 평균인데 왜 갑자기 저렇게 되나여..? 수학식으로 써서 보여줘.. 보여줘... 확통 다 헛배웠다 제발 알려줘 제발 고민해줘 나 대신 해줘해줘
> [220401] NY

- BOJ/Data_Structure/17073-나무_위의_빗물-GH.py
여러분 벌써 4월이에요...
이 스터디를 1월부터 시작했던 것 같은데...
시간이 어떻게 이렇게 됐지요... .... 더 멋잇는 댕발자가 되어봐요.. 짱짱맨들아!!!\
> https://www.acmicpc.net/source/41359271
> 880ms
> [220401] GH

- Programmers/서울에서_김서방_찾기-YJ.py
> [220402] YJ

- Programmers/서울에서_김서방_찾기-MH.py
> [220402] MH

- Programmers/서울에서_김서방_찾기-NY.py
> [220402] NY

- Programmers/서울에서_김서방_찾기-GH.py
> [220402] GH

- BOJ/Tree/5639-이진_검색_트리-YJ.py
https://www.acmicpc.net/source/41421457
오늘 다시보니깐 저번에 거의 다 푼거였더라구요 
왜 꼭 한번에 못푸는지 🫠
> 3984ms
> [220403] YJ

- BOJ/Tree/6416-트리인가?-NY.py
> [220403] NY

- BOJ/Tree/6416-트리인가-MH.py
개미는..뚠뚠...오늘도...논패스...
휴우우ㅜ 카페가 추워서 집가야겠어요 (핑계)
누가 트리인가 좀 풀어봐...
> [220403] MH

- BOJ/Tree/1967-트리의_지름-YJ.py
감도 못잡고 있다가 트리의 지름 구하는 방법 쳤더니 나온 문장..^^ 어라라 같은 문제~~~?
```
트리의 지름을 구하는 방법은 다음과 같다.
임의의 노드 x에서 가장 먼 거리에 있는 노드 a를 찾는다.
노드 a에서 가장 먼 거리에 있는 노드 b를 찾는다.
트리의 지름은 a와 b를 연결하는 경로이다.
지름 = a - b
출처: https://bedamino.tistory.com/15
```
많은 도움이 되었읍니다 ㅎㅎ ㅠ
> 96ms
> [220404] YJ

- BOJ/Data_Structure/9375-패션왕_신해빈-GH.py
어휴.. 절대 트리가 풀기 싫어서가 아니고
하하하
해빈친구가 얼마나 패션왕인지 궁금해서 풀어봤어요...
ㅎㅎㅎ...
이번 주도 우리 힘내 보아요 ><
> https://www.acmicpc.net/source/41458663
> 88ms
> [220403] GH

- Programmers/소수_찾기-NY.py
소수 찾기 못해서 40분 푼 여성 어떄요 하... 바보.. 바보....
> [220405] NY

- BOJ/Tree/소수_찾기-MH.py
에라토스테네스의 체 사용해서 풀어보고 싶었는데 시간초과 논패스 나와서 그냥.. 풀던대로 풀었어요
다른 사람 풀이보니까 맨 위에 나오는 방식이 제가 생각하던 것 같은데 일요일에 다시 공부해야겠어요 ,,,,
7점 받음 얏호!
> [220405] MH

- Programmers/소수_찾기-YJ.py
> [220405] YJ

- BOJ/Tree/3584-가장_가까운_공통_조상-NY.py
부모 관계만 nodes에 추가해주고 부모들을 타고 올라가면서
더해준 뒤에 이중 for문으로 비교해줬어용
Set으로 하려고 했는데 생각해보니 그러면 가까운 노드를 못 찾게 되는 에러가 발생할 것 같아서 이렇게 했슴니다
시간 초과 날까봐 긴장했는데 다행이었따 휴~
https://www.acmicpc.net/source/41567676
> 108ms
> [220406] NY

- BOJ/Tree/3584-가장_가까운_공통_조상-YJ.py
푼지 40분돼서.. 일단 못풀고 커밋하는데
루트 구하는 거 했고.. (이거 필요한건지 잘모르겠긴함 근데 dfs돌려고 구했음)
커밋하면서 생각한건데 공통 조상노드 구해야하는 x, y의 공통 부모 노드 찾아서 depth 비교해주면 되지않나 싶어요????
> [220406] YJ

- BOJ/Tree/3584-가장_가까운_공통_조상-MH.py
거의 뭐.. 하드코딩했는데요
A, B 각각 자기 자신 포함해서 모든 부모를 저장한 다음 비교하는 방식입니다
시간 초과날까봐 긴장했으요
http://boj.kr/0f96246fbac748e896df785c752f163a
> 100ms
> [220406] MH

- Programmers/수박수박수박수박수박수?-NY.py
> [220407] NY

- BOJ/Data_Structure/3584-가장_가까운_공통_조상-GH.py
흠냥
생각보다 시간이 적게 나와서 당황.. 했어요
오히려 좋아
> https://www.acmicpc.net/source/41614854
> 96ms
> [220406] GH

- Programmers/수박수박수박수박수박수?-YJ.py
> [220407] YJ

- Programmers/수박수박수박수박수박수-MH.py
> [220407] MH

- BOJ/Tree/9489-사촌-YJ.py
https://www.acmicpc.net/source/41704562
하 너무 뿌듯해요!!!!!!!!
depth 같은 애들끼리 놓고 풀려다가 할아버지 노드 같은 손자 노드들을 찾아서 쏵 훑어주면 되더라구요 근데 부모노드는 같으면 안됨 그것이.. 사촌이니깐 끄덕
> [220408] YJ

- Programmers/수박수박수박수박수박수-GH.py
> [220407] GH

- BOJ/Data_Structure/21942-부품_대여장-NY.py
- BOJ/Tree/6416-트리인가?-NY.py
- BOJ/Tree/9489-사촌-NY.py
- Programmers/문자열을_정수로_바꾸기-NY.py
백준은 다 해결을 못했꾸용 ㅜ ㅜㅜ
예전에 이것저것 뭔가... 커밋 덜 한 것 같은..? 코드들도 같이 올렸서요 긁적
> [220409] NY

- BOJ/Data_Structure/9489-사촌-GH.py
- Programmers/문자열을_정수로_바꾸기-GH.py
어제 거..
풀엇는데 커밋하는 걸 까먹어서
같이 올려요... 뿌엥
첫 번째 for문 조건 고민 마니 햇는데... 모르겟어서 다른 분 거 참고했다는 건 안 비밀입니다...
온전히 이해는 했찌만... 다음에 짜 보라고 하면 잘 짤 수 있을지 자신은 없어요
> https://www.acmicpc.net/source/41735638
> 1488ms
프로그래머스는.. 이렇게 풀어도 되나 싶으ㅡㄴ데.......
그렇게 됏습니다. 양심에 찔리는군
> [220409] GH

- Programmers/문자열을_정수로_바꾸기-YJ.py
문제의 의도가 이게 아닐 것 같지만 당당하게 이렇게 풀었습니다
0.1초 풀이
> [220409] YJ

- BOJ/Tree/9489-사촌-NY.py
아잇 ㅜㅜㅜ 어제 아침에 사촌 다시 풀었는데 업데이트 코드 풀리퀘를 안날렸네요 ㅜㅜ
커밋한건 아침이니까.. 봐주시술..
근데 난 또 논패스... 어쩔티비..
> [220410] NY

- BOJ/Tree/3584-가장_가까운_공통_조상-YJ.py
https://www.acmicpc.net/source/41797836
나름 원하는 대로 짠 것 같아요 근데 너무 많이 틀린.... 
> 120ms
> [220411] YJ

- BOJ/Data_Structure/1967-트리의_지름-GH.py
BFS 말고 다익스트라 알고리즘으로 푼 풀이가 흥미로워서
오늘 이 코드.. 뽀려가지고 구조 이해햇습니다..
알고리즘 배운 건 다 까먹음 ;ㅅ;
> [220410] GH

- Programmers/소수_찾기-MH.py
트리하기 싫어서 애써 눈돌리기..
소수 찾기 다시 풀어봤으요..
> [220410] MH

- BOJ/Tree/20924-트리의_기둥과_가지-NY.py
아.. 진짜 요즘 백준 계쏙 틀려서 일요일에 풀 거 쌓이는데
일요일에도 해결 못하고 이쑴 ㅜ... 하..
이거 지금 저 segFault 에러로 4번 틀림.. 덕지덕지 코드 붙여서 더러워짐.. 으앙 ㅜ... 으앙..
> [220411] NY

- BOJ/Tree/20924-트리의_기둥과_가지-MH.py
아 뭔가 풀 수 있을 것 같은데 갑자기 할일이 생겨서
내일 풀래요..
> [220411] MH

- BOJ/Data_Structure/20924-트리의_기둥과_가지-GH.py
커밋 메시지를 잘못 써서 다시 커밋햇어요..
maxBranch 찾는 거랑.. 예외만 잘 구하면 뭐...
어떻게든 되겟죠..
나는 진짜 트리가 싫다..(나무는 좋아함)
https://github.com/uujinn/Algorithm-Study/pull/342/commits/22c2e88a8f2756570ceaa59ef2e2280d642cd16a 얩니다..
> [220411] GH

- Programmers/시저_암호-NY.py
숏코딩하고 싶었는디.. 결국 그냥 했따
당당 6점 받아따!
> [220412] NY

- Programmers/시저_암호-GH.py
오...
파이썬에서 아스키 값 받아주는 함수 있는 거 처음 알앗는데
생각해 보니 있을 것 같은 함수네..
검색하다가 알아냇어요.. 오예
> [220412] GH

- Programmers/시저_암호-MH.py
미니는.. 시저암호.. 시저시저....
죄송합니다
7점 받아서 기뻤어요 꺄륵
> [220412] MH

- Programmers/시저_암호-YJ.py
ㅜㅜ 다들 문제 푸시고 코드 한번만 봐주세요
테스트케이스 + 질문에 나와있는 케이스 다 되는데.. 왜 통과를 못하니..
> [220412] YJ

- BOJ/Tree/4256-트리-MH.py
아 일단... 양심없지만 ...올릴게요
밤에 수정할게요................
> [220413] MH

- BOJ/Data_Structure/4256-트리-GH.py
후위순서로 변경한 리스트를 반환하는..
그런 건데
어렵네요
트리는 진짜 왜 그럴까
> [220413] GH

- BOJ/Tree/4256-트리-NY.py
- Programmers/약수의_합-NY.py
왜요.. 트리 컬렉터 같아요?
하.. 걍.. 몰겠떠,.,., 풀 수 있을 것 같았는데 ㅜㅜ.. 고민 많이 했는데.. 응..아니야..
> [220413] NY

- Programmers/약수의_합-YJ.py
> [220414] YJ

- Programmers/약수의_합-GH.py
흠냥.. for문이랑 if문 한 줄로 썻어요
근데 1점 받음 뿌엥
> [220414] GH

- Programmers/약수의_합-MH.py
> [220414] MH

- BOJ/Tree/2263-트리의_순회-YJ.py
https://www.acmicpc.net/source/42001301
저번이랑 비슷하게 루트 출력하고 왼쪽 오른쪽 재귀로 풀었슴다
> 340ms
> [220415] YJ

- BOJ/Tree/2263-트리의_순회-MH.py
- BOJ/Tree/4256-트리-MH.py
얼마만의 tree 패스인지....
해도해도..어렵다
예전에 4256 트리 문제도 비슷했던 것 같은데 풀어야겠어요..
http://boj.kr/0837c04bfa8e4fd2b46b7e0d14d3cd82
> 324ms
> [220415] MH

- BOJ/Tree/4256-트리-NY.py
저번 문제가 오늘 문제랑 비슷해서 일단 저번 문제부터 해결해떠요 ㅜㅜ
비슷한 원리 같은데 오늘 문제는 내일로 스리슬쩍 미뤄보겠습니다
https://www.acmicpc.net/source/42021934
> 640ms
> [220415] NY

- Programmers/이상한_문자_만들기-MH.py
와앙 9점 냠냠
첨에 문제 제대로 안읽고 단어 사이 공백 하나씩 집어넣은 사람 그게 바로 나애요
> [220416] MH

- Programmers/이상한_문자_만들기-YJ.py
> [220416] YJ

- Programmers/이상한_문자_만들기-NY.py
> [220416] NY

- BOJ/Data_Structure/2263-트리의_순회-GH.py
중위,, 후위순회로 전위를 알아내기... 좌우 나눠서 세어주기..
> https://www.acmicpc.net/source/42005151
> 308ms
> [220415] GH

- BOJ/Tree/9372-상근이의_여행-YJ.py
기가노드 모르겠어요.. 허ㅝ엉..
트리 실버 문제라도 풀어보려고 풀었습니당
풀고나서 다른 풀이 보는데... 걍 4줄 컷으로 풀 수 있는 다른 방법 있음.. 씁슬해지기 나만또 박치기지
> [220417] YJ

- BOJ/Tree/20924-트리의_기둥과_가지-MH.py
트리의 기둥과 가지.. 블로그의 도움을 받아.....
한 60% 밖에 이해 못 한 듯.......
뿌애애ㅐ애앵 누가 풀고 설명 좀 해주세요............
http://boj.kr/17c919e7cdd645f98e8654a7a4996cc5
> 804ms
> [220417] MH

- BOJ/Data_Structure/20924-트리의_기둥과_가지-GH.py
- Programmers/이상한_문자_만들기-GH.py
흐앙..
토요일 문제 풀어 놓고 커밋 안 한 사람 나야 나 ^^.. ....
기가노드 어쩌고 하는 문제도.. 업데이트햇습ㄴㅣ다......
(--)(__)
> [220417] GH

- BOJ/Tree/2250-트리의_높이와_너비-YJ.py
> [220418] YJ

- BOJ/Tree/2250-트리의_높이와_너비-MH.py
코드에 주석으로 어떤 식으로 작동하는지 써놨으니 보시고 이해가 된다면... 따봉
우선 tree에 인덱스 이용해서 (left, right)로 저장하고 중위순회로 depth를 level 리스트에 구해줬어용
그리고 level을 거꾸로 저장한 level_reverse 리스트 만들어서 find로 인덱스 이용해 너비 구해주기 ~.~ 근데 지금 생각해보니까 굳이 reverse 리스트를 만들 필요가 있었을까
드르렁
http://boj.kr/9870acbfb9ed4930a94200419ecefd25
> 88ms
> [220418] MH

- BOJ/Data_Structure/2250-트리의_높이와_너비-GH.py
중위순회..로 돌고 인덱스마다.. 레벨을 두고..?
레벨 나눈 거에서 인덱스 숫자 차이를 구해 볼까 했는데
도저히 못하겟어요..
일요일의 내가 할 수 있기를!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
중위순회 ㅋㅗ드 돌려쓰기 맞습니다
> [220418] GH

- Programmers/자릿수_더하기-GH.py
> [220419] GH

- Programmers/자릿수_더하기-YJ.py
> [220419] YJ

- BOJ/Math/5618-공약수-NY.py
약수 구하는 함수 만들어서 각자 set에 저장하고 교집합 찾는걸로 풀었는데
뭔가 이거 .. 아닌것..같기도..???.. 
https://www.acmicpc.net/source/42213432
> 72ms
> [220420] NY

- BOJ/Tree/5618-공약수-MH.py
> [220420] MH

- BOJ/Data_Structure/5618-공약수-GH.py
> [220420] GH

- Programmers/자연수_뒤집어_배열로_만들기-MH.py
> [220421] MH

- Programmers/자연수_뒤집어_배열로_만들기-NY.py
> [220421] NY

- Programmers/자연수_뒤집어_배열로_만들기-GH.py
> [220421] GH

- BOJ/Math/공약수-YJ.py
https://www.acmicpc.net/source/42218009
시험기간이라고 백준이 효도하네.. 시간은 흐린눈 
> 1276ms
> [220420] YJ

- BOJ/Math/22864-피로도-NY.py
부등호 잘못 포함해서 2번 틀린 사람 어때
https://www.acmicpc.net/source/42324582
> 72ms
> [220422] NY

- BOJ/Data_Structure/22864-피로도-GH.py
레전드 피로함..
번아웃 오고 그냥.. 일을 하지 마시길 바랍니다
가성비 짱구림
> https://www.acmicpc.net/source/42325994
> 72ms
> [220422] GH

- Programmers/자연수_뒤집어_배열로_만들기-YJ.py
- Programmers/정수_내림차순으로_배치하기-YJ.py
> [220423] YJ

- Programmers/정수_내림차순으로_배치하기-MH.py
첨에 sorted 생각못하고 하나하나씩 max찾아서 인덱스 찾아 지운건 안비밀
> [220423] MH

- Programmers/정수_내림차순으로_배치하기-GH.py
x토할번햇어요
내...위장...살려..................
> [220423] GH

- Programmers/정수_내림차순으로_배치하기-NY.py
아직도.. 가끔 list로 리턴되는게 sort()인지 sorted()인지 헷갈릴때가 있어요..
> [220423] NY

- Programmers/정수_내림차순으로_배치하기-YJ.py
> [220424] YJ

- BOJ/Tree/6416-트리인가-MH.py
응응... 논패스 해줄게
이거 누구 푼 사람 있나요......
블로그도 찾아봤는데 예전이랑 그 조건이 바뀐 듯..
http://boj.kr/f118dab18cce46cfacfc8dad5ce41b94
> [220424] MH

- BOJ/Tree/2745-진법_변환-MH.py
일여일에 int안쓰고 n진법 > 10진법 하는거 한번 해봐야겠으요
http://boj.kr/273bbcf99af24bb9b49a21a49ed18dc9
> 76ms
> [220425] MH

- BOJ/Math/2749-진법_변환-YJ.py
https://www.acmicpc.net/source/42416415
프로그래머스인줄 ^_^
> 68ms
> [220425] YJ

- BOJ/Math/2745-진법_변환-NY.py
이거 옛날에 풀었던 건데 옛날엔 직접 구현했었다는...
이번에는 간단하게 int로 뚝딱 해결 완
https://www.acmicpc.net/source/42447835
> 68ms
> [220425] NY

- Programmers/정수_제곱근_판별-MH.py
2점 받았어요
% 1 == 0으로 정수인지 아닌지 판별하는 식도 있더라구요
저는 int 씌운거랑 안씌운걸로 판별했습니다
> [220426] MH

- Programmers/정수_제곱근_판별-NY.py
2점 받았는데 풀고 나서 보니 참... 음.. 복잡하게 푼 것 같?아요?감사합니다?
> [220426] NY

- BOJ/Data_Structure/2250-트리의_높이와_너비-GH.py
- BOJ/Data_Structure/2745-진법_변환-GH.py
휴우... 지난주 월요일 문제 다시 풀어꾸용...
오늘 문제는 냅다 형변환 해 줄게.. 레전드 성의없는 코드 주의
> https://www.acmicpc.net/source/42453544
> 72ms
> [220425] GH

- Programmers/정수_제곱근_판별-YJ.py
int로 감싸준거랑 아닌거랑 비교해서 정수인지 판별했습니다
> [220426] YJ

- BOJ/Math/1110-더하기_사이클-NY.py
이것도 예전에 풀었던거네요.. 예전에는 왜인지 모르겠지만? 쬐끔 더 복잡하게 풀었었네요..
오늘은 그냥.. 나쁘지 않게 푼 것?같아요?
https://www.acmicpc.net/source/42503645
> 68ms
> [220427] NY

- BOJ/Math/1110-더하기_사이클-YJ.py
https://www.acmicpc.net/source/42531971
original을 애초에 01 이런식으로 앞에 0 붙인걸로 해야하는데 다르게 비교하니깐 계속 틀렸어요 포기할뻔ㅋ
> 68ms
> [220427] YJ

- BOJ/Math/1110-더하기_사이클-MH.py
첨에 문제가 안읽혀서 왼쪽이 어쩌고 붙어서... 여러번 읽었어요
http://boj.kr/f9c2398447ba4154a7ad9c996f578ad1
> 68ms
> [220427] MH

- Programmers/제일_작은_수_제거하기-GH.py
> [220428] GH

- Programmers/제일_작은_수_제거하기-MH.py
> [220428] MH

- BOJ/Math/2609-최대공약수와_최대공배수-MH.py
내일.. 다시 풀게요...................
시간초과 왜....너ㅏ.......
> [220429] MH

- BOJ/Data_Structure/2609-최대공약수와_최소공배수-GH.py
유클리드호제법.
으로 호로로로로록
> https://www.acmicpc.net/source/42611511
> 72ms
> [220429] GH

- Programmers/제일_작은_수_제거하기-NY.py
4점 받았는디.. 이게 썩 좋은 풀이라고 생각되지는 않아요..? 
min 시간 복잡도 O(N)
remove 시간 복잡도 O(N) 이라 결국 O(N^2) 쓴 거라서..
그래서 O(N) + O(N) 형식으로도 풀어봤는데 점수 자체는 똑같아요.. 하지만 정수 값이 진짜 엄청 많이 들어오고 정수 값 자체가 컸으면 이게 더 낫지 않나? 싶은 생각이 들어요
```
def solution(arr):
min_val = min(arr)
answer = []
for a in arr:
if a == min_val: continue
else: answer.append(a)
return answer if answer else [-1]
```
> [220428] NY

- BOJ/Math/2609-최대공약수와_최소공배수-YJ.py
https://www.acmicpc.net/source/42605368
> 76ms
> [220429] YJ

- Programmers/짝수와_홀수-MH.py
num % 2 를 조건으로 해서 1이 나오면 'Odd' 아니면 'Even' ~~
> [220430] MH

- Programmers/짝수와_홀수-GH.py
> [220430] GH

- Programmers/짝수와_홀수-YJ.py
> [220430] YJ

- BOJ/Math/2609-최대공약수와_최대공배수-MH.py
유클리드 호제법.. 재귀로.. 흠녀녕
> 68ms
http://boj.kr/c506a271bf814e33b99c84e1ab3b7a7b
> [220501] MH

- Sunday/문자열_압축-YJ.py
> [220501] YJ

- Programmers/짝수와_홀수-NY.py
오늘 프로그래머스라 너무 다행이다 ㅜ..
어제 못 푼 건 벌금 낼게요.. 돈아 어디가 가지마
> [220430] NY

- BOJ/Math/1934-최소공배수-YJ.py
https://www.acmicpc.net/source/42740793
이렇게 날로 먹어도 되는 걸까?
> 152ms
> [220502] YJ

- BOJ/Math/1934-최소공배수-NY.py
슈슉..슈슉..풀었다
https://www.acmicpc.net/source/42769281
> 68ms
> [220502] NY

- BOJ/Data_Structure/1934-최소공배수-GH.py
2609번 문제랑
똑같군요...
오히려 좋아
> https://www.acmicpc.net/source/42762534
> 88ms
> [220502] GH

- Programmers/최대공약수와_최소공배수-MH.py
> [220503] MH

- Programmers/최대공약수와_최소공배수-YJ.py
> [220503] YJ

- Programmers/최대공약수와_최소공배수-NY.py
다행이다.. 오늘 프로그래머스에.. 최대공약수 최소공배수라서..
> [220503] NY

- BOJ/Math/2581-소수-YJ.py
https://www.acmicpc.net/source/42848239
> 76ms
> [220504] YJ

- BOJ/Data_Structure/2581-소수-GH.py
하핫 어제 거 풀고 안 올렷네요
조용히 입금..
원래 솟수~랑 범위를 따로따로 설정햇는데
시간 초과 날까 바..
한 번에 하는 코드로 참고해서.. 바깟다네요 훨씬 간단해 보여서 굿
> https://www.acmicpc.net/source/42859293
> 996ms
> [220504] GH

- BOJ/Math/2581-소수-MH.py
그래요... 제가 소수 논패스입니다..
왜 틀린지 모르겠어요...
집중이 안돼요...
> [220504] MH

- BOJ/Math/2581-소수-NY.py
그닥 깔끔하게 푼 것 같지는 않아욥..? 
https://www.acmicpc.net/source/42858581
> 68ms
> [220504] NY

- Programmers/콜라츠_추측-NY.py
> [220505] NY

- Programmers/콜라츠_추측-MH.py
> [220505] MH

- Programmers/콜라즈_추측-YJ.py
> [220505] YJ

- Programmers/콜라츠_추측-GH.py
> [220505] GH

- BOJ/Data_Structure/11653-소인수분해-GH.py
다 분해될 때까지 냅다 루프 돌리는 여성 어떄?
> https://www.acmicpc.net/source/42936908
> 956ms
> [220506] GH

- BOJ/Math/11653-소인수분해-NY.py
아놔 이거 커밋할때 터미널로 했더니 글자 먹혀서 이상하게 됐넹
ㅎ헤ㅔ헤..
에라토스어쩌고로 소수 다 찾고 그 소수에서 작은 애들부터 먼저 나누기 해서 print 했어요
https://www.acmicpc.net/source/42907119
> 2980ms
> [220506] NY

- BOJ/Math/11653-소인수분해-MH.py
에라토스 어쩌고로도 한 번 풀어보고 싶네요 그럼 이만
http://boj.kr/af24f07732d84c6aaa9be211d845142d
> 1112ms
> [220506] MH

- BOJ/Math/11653-소인수분해-YJ.py
https://www.acmicpc.net/source/42936333
까먹구 커밋 안할뻔..!~!! 에라토스테네스의 체로 안푼것 같아요...
> 72ms
> [220506] YJ

- Programmers/평균_구하기-YJ.py
> [220507] YJ

- Programmers/평균_구하기-GH.py
> [220507] GH

- Programmers/평균_구하기-MH.py
> [220507] MH

- Programmers/평균_구하기-NY.py
프로그래머스 Level 1 문제들이 점점 고갈되는걸 보면 슬퍼요
> [220507] NY

- BOJ/Math/2581-소수-MH.py
> [220508] MH

- Programmers/최대공약수와_최소공배수-GH.py
d유클리드 호제법... 으로 풀엇던 문제 올리는 거 까먹엇는데
코드 완성해서 업데이트 합니다용가리
모두 행복한 어버이날 보내세요 ~,~
> [220508] GH

- BOJ/Math/1978-소수_찾기-YJ.py
https://www.acmicpc.net/source/43066599
> 68ms
> [220509] YJ

- BOJ/Math/1978-소수_찾기-MH.py
소수찾기 장인되벌임
http://boj.kr/7e461c8a08ad413b911d440e92df2d20
> 68ms
> [220509] MH

- BOJ/Data_Structure/1978-소수_찾기-GH.py
먼가... 이해했는데
이해가 안 돼서
약간 로직 세우다가 짱나가지고
지나가던 블로그 도움을 받앗어요.. 감ㅅ ㅏ 합니다
사랑해요
> [220509] GH

- BOJ/Math/1978-소수_찾기-NY.py
https://www.acmicpc.net/source/43065819
> 68ms
> [220510] NY

- Programmers/하샤드_수-MH.py
> [220510] MH

- Programmers/하샤드_수-GH.py
> [220510] GH

- BOJ/Math/2960-에라토스테네스의_체-YJ.py
https://www.acmicpc.net/source/43167910
나 좀 무식하게 풀었을지도..
> [220511] YJ

- BOJ/Math/2960-에라토스테네스의_체-MH.py
> [220511] MH

- BOJ/Data_Structure/2960-에라토스테네스의_체-GH.py
에라토스테네스..
아리스토텔레스..
> https://www.acmicpc.net/source/43172237
> 68ms
> [220511] GH

- Programmers/핸드폰_번호_가리기-GH.py
> [220512] GH

- BOJ/Math/핸드폰_번호_가리기-MH.py
> [220512] MH

- BOJ/Math/5347-LCM-MH.py
math가고.. greedy 오는 중..
http://boj.kr/2f8a66949de940b58ce7fcee92804a27
> 72ms
> [220513] MH

- BOJ/Math/5347-LCM-YJ.py
https://www.acmicpc.net/source/43231458
내공냠냠
> 68ms
> [220513] YJ

- BOJ/Math/5347-LCM-NY.py
썩 잘 짠 것 같지는..않지만 어쨌든 했따
https://www.acmicpc.net/source/43259264
> 72ms
> [220513] NY

- Programmers/행렬의_덧셈-MH.py
> [220514] MH

- BOJ/Data_Structure/5347-LCM-GH.py
제가 당연히 말햇겟죠?
파이썬 사랑한다고..
r긍데 코테에서 이런 라이브러ㅣ리.. 못 쓰게 하는 곳도 많겟죠? 힝
> https://www.acmicpc.net/source/43229026
> 68ms
> [220513] GH

- Programmers/행렬의_덧셈-NY.py
마지막 테스트 케이스 시간 오래 걸렸는디.. 이거 맞나..? 괜찮나?...
> [220514] NY

- Programmers/행렬의_덧셈-YJ.py
> [220514] YJ

- Programmers/행렬의_덧셈-GH.py
> [220514] GH

- BOJ/Math/2553-마지막_팩토리얼_수-YJ.py
https://www.acmicpc.net/source/43340832
math에 포함되어있는 문제 풀었어요~
> 228ms
> [220515] YJ

- BOJ/Math/2960-에라토스테네스의_체-MH.py
왜 항상 백준 68ms랑 72ms 많이 나오는 것 같지
http://boj.kr/af553698979c47348886887c3c6583d6
> 68ms
> [220515] MH

- BOJ/Data_Structure/1669-멍멍이_쓰다듬기-GH.py
문제 이름이 귀여워서
ㅎㅅㅎ
> https://www.acmicpc.net/source/43346727
> [220515] GH

- BOJ/Math/4134-다음_소수-NY.py
인덱스 에러 해결했더니 갑자기 이제 메모리 초과됨.. 도와줘 친구들아
> [220516] NY

- BOJ/Math/4134-다음_소수-YJ.py
https://www.acmicpc.net/source/43382596
> 1776ms
> [220516] YJ

- Programmers/x만큼_간격이_있는_n개의_숫자.py
> [220517] YJ

- BOJ/Math/4134-다음_소수-MH.py
- Programmers/x만큼_간격이_있는_n개의_숫자-MH.py
근데 x가 음수일 때 저렇게 처리할거면 문제 설명에 x만큼 증가한다고 하면 안되지 않나... 흠냥
> [220517] MH

- BOJ/Data_Structure/4134-다음_소수-GH.py
- Programmers/x만큼_간격이_있는_n개의_숫자-GH.py
어제.. 풀고.... 커밋 안 해서 같이 올려여......
시간초과나서그냥냅다커밋하기.
이에 반해 프로그래머스는~ 사랑스럽고 소중해요~
> [220517] GH

- BOJ/Math/21920-서로소_평균-NY.py
흠... 시간이 너무 오래 걸린 것 같아요
최대공약수를 하나씩 다 비교해서 1일때를 더해주고 count해줘서 나눠줬는데 최대공약수 구하는 함수 자체가 재귀라서...
더 좋은 방법 있으신 분들의 풀이를 기대합니당 ₍ᐢ ɞ̴̶̷  ̫ ɞ̴̶̷ ᐢ₎ 
https://www.acmicpc.net/source/43455803
> 1140ms
> [220518] NY

- BOJ/Math/21920-서로소_평균-MH.py
나 왜 틀렸는지 모르겠어요,.,,,,,,,,
첨에 math 라이브러리 안쓰고 재귀하는 GCD 함수 정의해서 채점했는데 틀렸댕..
그래서 math 라이브러리로 채점했는데 또 틀렸댕
왜지감자
> [220518] MH

- BOJ/Math/21920-서로소_평균-YJ.py
https://www.acmicpc.net/source/43472926
`최대공약수가 1이면 서로소`로 풀었습니다.
> 412ms
> [220518] YJ

- BOJ/Data_Structure/21920-서로소_평균-GH.py
으엥..
논패스 돼서 언니들이랑 미니는 어뜨케 풀엇나~ 하면서 봣는데
유진웅니랑 똑같은데 why..
미니랑 똑같은 상황이에ㅛ...... 잘못이 뭐지.......................
디버깅도 해 봣는데 값 제대로 들어가던데.. ........
> [220518] GH

- Programmers/직사각형_별찍기-NY.py
파이썬의 기억이 떠오르는.. 그런 문제네요.. 이제 이게 레벨1 끝이다.. 좋았던 시절아 안녕..
> [220519] NY

- Programmers/직사각형_별찍기-YJ.py
> [220519] YJ

- BOJ/Math/21920-서로소_평균-MH.py
- Programmers/직사각형_별찍기-MH.py
언니들의 도움을 받아 어제것도 패쓰,,
math 라이브러리 쓰니까 384ms인데 재귀로 구현하니까 1248ms더라구요
http://boj.kr/c0522ceef9d84130ad64b23d69b7c5d9
> [220519] MH

- Programmers/직사각형_별찍기-GH.py
> [220519] GH

- BOJ/Data_Structure/9613-GCD_합-GH.py
와우우
파이썬에는 없는 게 도대체 뭘까? ??? ????
> [220520] GH

- BOJ/Math/9613-GCD_합-YJ.py
https://www.acmicpc.net/source/43568948
> 68ms
> [220520] YJ

- Programmers/신고_결과_받기-YJ.py
> [220521] YJ

- Programmers/신고_결과_받기-MH.py
뭔가 난 데이터 다 저장하고 보는 타입인데 굳이 메모리안쓰고도 할 수 있는 방법이 있어서 슬프내용
> [220521] MH

- Programmers/신고_결과_받기-GH.py
헉 프로그래머스 레벨 1이 끗낫다..
좋은 날 다 갓다..
다른 사람들이 푼 거 보니까 set(report)로... 멋지게 풀엇던데..
.......... 아직도 마니 멀엇군요
> [220521] GH

- Programmers/신고_결과_받기-NY.py
생각 많이 안하고.. 그냥 슉 풀어버려서 딱히 좋은 코드라고 생각되지는 않아요.. 가독성도 엄청 떨어지고 딕셔너리도 복잡하고
5점 받았습니당.. 중복 체크도 생각해보니까 [a][0]을 set으로 뒀으면 됐을텐데 하는.. 아쉬움이 이래저래
> [220521] NY

- Programmers/신고_결과_받기-YJ.py
> [220522] YJ

- BOJ/Math/4134-다음_소수-MH.py
에라 어쩌고로 풀려다가 잘안돼서 유진언니 코드보고 다시 풀었어요
짱유진 사랑해
http://boj.kr/3e91d51a8657411bb73a38768e9ef4eb
> 1660ms
> [220522] MH

- BOJ/Data_Structure/2553-마지막_팩토리얼_수-GH.py
지난주에 유진언니가 푼 문제
양민수 햇어욤~~
> https://www.acmicpc.net/source/43649517
> 156ms
아니근데 그건그렇고
이분 코드 보실 분 광기 레전드임
https://www.acmicpc.net/source/42801884
> [220522] GH

- BOJ/Math/21919-소수_최소_공배수-MH.py
소수들의 최소공배수면 곱해주기만 하면되는데 lcm 찾고있었던 나 제법 바보같아요
http://boj.kr/d8c9d9e2219c435c8f3d8fd038298355
> 184ms
> [220523] MH

- Programmers/21275-폰_호석만-YJ.py
부분 성공이래요 당연함 두 번째 예제 통과 못함 잉~~~~
그럼 틀린거지 왜 맞았다그래~~~~~
> [220523] YJ

- BOJ/Math/21919-소수_최소_공배수-NY.py
소수 판별 함수를 이용했고 set() 써서 똑같은 애들이 안 들어오게 방지해주었슴니당
https://www.acmicpc.net/source/43661951
> 544ms
> [220523] NY

- Programmers/문자열_압축-GH.py
> [220524] GH

- Programmers/문자열_압축-MH.py
그냥 유진언니꺼 보고 따라한 사람 됨
ㅇㅇ.. 다른 사람 풀이보니까 기발한거 많아보이던데.. 일요일에 다시 공부하겠삼..
> [220524] MH

- BOJ/Math/21919-소수_최소_공배수-YJ.py
> [220525] YJ

- Programmers/21275-폰_호석만-MH.py
사실 나 부분 맞습니다 기대했는데 다 맞아서 놀랐어
http://boj.kr/c9b2c4ad992c4a439ccf62a216554a55
> 72ms
> [220525] MH

- BOJ/Math/21275-폰_호석만-NY.py
...우린 이걸 논패스..?라고..불러요..?
24개중에 10개 맞았으면 이걸 부분 패스라고 하긴 좀... ^^..
반례 던져주실 분들 구합니다
> [220525] NY

- Programmers/오픈채팅방-NY.py
> [220526] NY

- Programmers/오픈채팅방_YJ.py
> [220526] YJ

- Programmers/오픈채팅방-GH.py
dictionary의 key 값을 이용햇어요~
2점 받음.. ㅜ ㅜ
> [220526] GH

- Programmers/오픈채팅방-MH.py
> [220526] MH

- BOJ/Math/1747-소수팰린드롬-MH.py
시간 이거 맞냐고..
예전에 풀었던 다음 소수 정답에 팰린드롬만 추가했더니 정답이네용 꿀!
http://boj.kr/454402b199114b02a88bcd994fdc887b 
> 4048ms
> [220527] MH

- BOJ/Math/1747-소수&팰린드롬-YJ.py
https://www.acmicpc.net/source/43841305
풀라고한대로 풀었어요 
시간이 엉금엉금
> 4096ms
> [220527] YJ

- BOJ/Math/1747-소수&팰린드롬-NY.py
1 처리 안해줘서 처음에 틀렸다가 고쳐서 맞았습니덩..
근데 시간 이렇게 오래 걸리는거 괜찮은걸까? ^^.. 이거 좀 비효율적인거같긴해요..~...
차라리 N보다 큰 소수들을.. 10개 단위?정도로 구하고 그 안에서 소수 값만 더해서 얘가 팰린드롬인지 체크하는게 나을지도..? 핫핫
https://www.acmicpc.net/source/43836376
> 4020ms
> [220527] NY

- Programmers/멀쩡한_사각형-MH.py
공식찾아내는데 블로그의 도움을 좀 받았어요..헤헤 긁긁
> [220528] MH

- BOJ/Data_Structure/1747-소수_팰린드롬-GH.py
소수랑 팰린드롬 각각 구햇서요
시간이 레전드다..
> https://www.acmicpc.net/source/43847314
> 4048ms
> [220527] GH

- Programmers/멀쩡한_사각형-YJ.py
여기까지 전에 풀어본 문제 ^^.. 헤헤
풀었다고하기도 그런게 규칙 못찾아서 이미 헤맨 전적 있음
아래 블로그 보고 아아 글쿤 이런걸 어케
아니아니
했어요
암튼 이런 규칙 못찾겠단 소리
눈치가 없는걸로 치자
주절주절
https://velog.io/@sem/프로그래머스-LEVEL2-멀쩡한-사각형-Python
> [220528] YJ

- BOJ/Math/11653-소인수분해-MH.py
pass했던 문제를 다른 방식으로 풀어서 non pass가 나온 경우 다들 어때
인덱스 에러 자꾸 나는데 혹시... 봐주실 분..
원래는 그냥 while문으로 풀었는데 에라토스테네스의 체로 풀어보고 싶어서 히잉
http://boj.kr/e49a7f6ae5b14eb4ace51a0c36900668
> [220529] MH

- BOJ/Data_Structure/21275-폰_호석만-GH.py
- Programmers/멀쩡한_사각형-GH.py
사각형 문제는 ㅜ 끙끙대다가 블로그 공식 보고 무릎을 탁 쳣어요..
이런 공식을 떠올리지 못하는 나..
좀 더 노력해야 할지도..
폰 호석만도 미니 말대로 추가하니까
전체패스 됏어요!!! 미니짱짱걸
> [220529] GH

- BOJ/Math/22943-수-NY.py
처음 커밋은 틀린 코드였고 두 번째는 잘못된 거 고쳐서 커밋했는데 시간 초과
세 번째도 완전 간단하게 나름 바꿔서 커밋했는데 시간 초과... 아.. ㄱ-..
> [220530] NY

- BOJ/Math/22943-수-MH.py
ㅇ너무 잠이와서... 일단 숫자 한번씩만 사용해서 만들 수 있는 수 Knums랑
소수들 리스트까지만 뽑았어요...
드르렁 내일 풀어야지
> [220530] MH

- Programmers/124_나라의_숫자-NY.py
> [220531] NY

- Programmers/124_나라의_숫자-YJ.py
> [220531] YJ

- Programmers/124_나라의_숫자-MH.py
> [220531] MH

- BOJ/Data_Structure/22943-수-GH.py
- Programmers/124_나라의_숫자-GH.py
꺄아
근데 사실 어제 거 다 못 풀엇어요..
오늘 다 해결할 수 잇을 거라 생각햇숴
124나라는.. 3진법 엇비슷한 거라고 생각하고 풀엇습니다~ ~~~
> [220531] GH

- BOJ/Dynamic_Programming/10870-피보나치_수_5-MH.py
오랜만에 피보나치~!
http://boj.kr/b2e91a5a85f7441eb69f2b23303540a1
> 68ms
> [220601] MH

- BOJ/Data_Structure/10870-피보나치_수_5-GH.py
오마이갓..
6월이에요...
> https://www.acmicpc.net/source/44044445
> 72ms
> [220601] GH

- Programmers/기능_개발-YJ.py
> [220602] YJ

- Programmers/기능개발-MH.py
> [220602] MH

- Programmers/기능_개발-GH.py
> [220602] GH

- BOJ/Dynamic_Programming/2839-설탕_배달-YJ.py
https://www.acmicpc.net/source/44104894
아줌마 못풀지
> 68ms
> [220603] YJ

- BOJ/Dynamic_Programming/2839-설탕_배달-MH.py
어라랑 조빱 문제인줄 알았는데 풀다보니 꽤 생각해야 하내요
아일요일에 풀게여..
> [220603] MH

- BOJ/Dynamic_Programming/2839-설탕_배달-NY.py
첨에 재귀로 풀었따가 시간초과..
구냥 dp라는 배열 만들어서 0부터 N까지 3이랑 5로 표현할 수 있는 경우 다 셌어요 ^^..
18이면 어차피 마지막에 3아니면 5 더해서 완성할테니까
dp[18] = min(dp[15] + dp[3], dp[13] + dp[5]) 이렇게 풀었습니덩
https://www.acmicpc.net/source/44109973
> 80ms
> [220603] NY

- Programmers/더_맵게-MH.py
> [220604] MH

- Programmers/더_맵게-YJ.py
처음에 리스트로 풀다가 제목에 힙이 써있어서 변경 ^-^... 힙 왜 까먹고 있었지
> [220604] YJ

- Programmers/더_맵게-NY.py
어제 안 푼 거 일욜날 풀기.. 나 이러다가 벌금으로 재산 거덜나겠어
> [220605] NY

- BOJ/Math/22943-수-YJ.py
블로그 글 보고 다시 풀었는데도 시간초과!!! ^^ 어쩐지 맞힌 사람 53명 다시 풀어봐야지.. 철푸덕
> [220605] YJ

- BOJ/Dynamic_Programming/2839-설탕_배달-MH.py
> [220605] MH

- BOJ/Data_Structure/2839-설탕_배달-GH.py
바보갓이 울고잇는 나..
> https://www.acmicpc.net/source/44138046
> 72ms
> [220603] GH

- BOJ/Dynamic_Programming/2748-피보나치_수_2-NY.py
아무생각없이 저번이랑 똑같네~~ 헤헤 재귀 꼬! 이랬다가 시간초과나서
다시 황급하게 바꿨습니다...
https://www.acmicpc.net/source/44208913
> 68ms
> [220606] NY

- BOJ/Dynamic_Programming/2748-피보나치_수-YJ.py
https://www.acmicpc.net/source/44213268
.　　　　\　　　|
　╲　　　　　　　　　　　╱
　　　　　\　　　　/
　　　╲　　　　　　　╱
　　╲　　 우와　　　╱
-　-　 재활용 성공 　-　-
　　╱　　　　　　　　╲
　　╱　　/
　　╱　　　　　\　　╲
　　　　　/　|　　\
　　　　 　　|
> 72ms
> [220606] YJ

- BOJ/Dynamic_Programming/2748-피보나치_수_2-MH.py
- BOJ/Tree/9489-사촌-MH.py
> [220606] MH

- Programmers/타겟_넘버-MH.py
패쓰입니당
다른 사람 풀이보고 기겁했잔아요 ..... 갈길이멀다..
> [220607] MH

- Programmers/타겟_넘버-YJ.py
그니까 DFS로 풀어야되겠다는건 알겠는데 모르겠는데
오렌지주스에 오렌지 0.1% 느낌으로 들어간 제 코드입니다.
> [220608] YJ

- BOJ/Math/1010-다리_놓기-MH.py
일단 커밋하고봐..
반례 다 맞는데 왜 틀렸지!?
http://boj.kr/8a150269b4d9425d96e9cabdaebbe077
> [220608] MH

- BOJ/Dynamic_Programming/1010_다리_놓기-YJ.py
당연히 조합이지~ 이러고 멋지게시간초과
DP였다.....
> [220609] YJ

- BOJ/Math/9655-돌_게임-MH.py
엥 이게맞네
> 68ms
http://boj.kr/4f609980d2494fcaaa55de33fcd1e5f1
> [220610] MH

- BOJ/Dynamic_Programming/9655-돌_게임-YJ.py
> [220611] YJ

- BOJ/Data_Structure/1010-다리_놓기-GH.py
- BOJ/Data_Structure/2748-피보나치_수_2-GH.py
- BOJ/Data_Structure/9655-돌_게임-GH.py
- Programmers/더_맵게-GH.py
- Programmers/짝지어_제거하기-GH.py
- Programmers/타겟_넘버-GH.py
앗농하세요.. 오랜만입니다..
주말에는 가족이 올라와서 컴터를 못 썻고..
평일에는 시험에 학회에.. 정신이 없어서 소홀햇습니다(구구절절)
지난주 거랑 이번 주 거.. 반반 올리려고 햇는데
새벽에 바선생이랑 눈 마주치고 잠 다 깨서 몇 개 안 남은 것도 다 풀어서..>> >................
다시 열심히 1일 1문제 달리겟슴니다!!!!!
> [220610] GH

- Programmers/행렬_테두리_회전하기-GH.py
저는 왼쪽 상단 기준 시계방향으로 업데이트 해 주엇다네요..
근데 참을성 잇게 잘 구하면 되는데
하다가 으아아악!! 해서.. 블로그의 도움 쫌 받앗습니다.
그래서 minimum도 업데이트 하면서 같이 구햇어요..
> [220611] GH

- BOJ/Data_Structure/10845-큐-YJ.py
https://www.acmicpc.net/source/44450951
왜 이거 풀었냐면
안풀었길래 ◠‿◠
> 100ms
> [220612] YJ

- Programmers/짝지어_제거하기-MH.py
문제를 보고 딱 이건 이렇게 풀어야겠다..라고 생각할 수 있는 그 날까지..
> [220612] MH

- Programmers/17626-Four_Squares-MH.py
블로그 참고 좀 해서... 완성.....
116ms
> http://boj.kr/1bf9484e71eb4d06baafe9601df726ed
> [220613] MH

- BOJ/Dynamic_Programming/17626-Four_Squares-YJ.py
https://www.acmicpc.net/source/44484733
> 120ms
> [220613] YJ

- Programmers/메뉴_리뉴얼-MH.py
다람쥐마냥 일요일 볼따구에 문제만 계속 넣는 중 ㅋㅅㅋ
> [220614] MH

- Programmers/메뉴_리뉴얼-YJ.py
문제를 잘못 이해해서 잘못 풀었읍니다 ^^ 일요일에 다시 풀어야지
> [220614] YJ

- Programmers/메뉴_리뉴얼-GH.py
너히 레스토랑..
메뉴 리뉴얼 하지 말고
걍 잇는 대로 팔아라.. 킹받으니까
> [220614] GH

- BOJ/1463-1로_만들기-MH.py
문제가 너무 안풀려서 블로그보고 이해했는데 세상에 천재가 너무 많다,,
http://boj.kr/31887b1df9bf44e28a0bb968920bc86d
> 620ms
> [220615] MH

- BOJ/Dynamic_Programming/1463-1로_만들기-YJ.py
> [220615] YJ

- BOJ/Data_Structure/1463-1로_만들기-GH.py
디피 늠무 어렵다...
처음에 아이디어 떠올리는 게 헬인 것 같습니다..
> 648ms
> [220615] GH

- Programmers/괄호_변환-YJ.py
- 처음에는 백준에 있는 VPS 문제랑 같은 문제인줄 알았어요
- 괄호 나오면 Stack 갈겨
- 차근차근 풀면 쉬운듯??
- ㄱㅅㅎㄴㄷ
> [220616] YJ

- Programmers/괄호_변환-GH.py
> [220616] GH

- BOJ/Dynamic_Programming/11726-타일링-YJ.py
> [220617] YJ

- BOJ/Dynamic_Programming/9095-1, 2, 3 더하기-MH.py
갑자기 분위기 피보나치..
http://boj.kr/2f217f202c304a3e8ed137c690bf99fc
> 72ms
> [220617] MH

- Programmers/뉴스_클러스터링-YJ.py
> [220618] YJ

- BOJ/Dynamic_Programming/17626-Four_Squares-NY.py
> [220613] NY

- BOJ/Data_Structure/9095-1,2,3_더하기-GH.py
디피라는 거..
어렵뜨아..
dfs로 푼 사람도 잇던데... 참고해 보겟습니다...
> 76ms
> [220617] GH

- Programmers/[1차]_뉴스_클러스터링-GH.py
굉장히
파이썬스럽게 짠 코드가 잇길래
같이 업데이트합니다
진짜.............. 파이써닉하다.
> [220619] GH

- BOJ/Dynamic_Programming/9095-1,2,3_더하기-YJ.py
https://www.acmicpc.net/source/44776703
규칙 찾기 재밌다(아님)
> 68ms
> [220620] YJ

- BOJ/Dynamic_Programming/2579-계단_오르기-MH.py
한글을 못 읽겠어요
http://boj.kr/731fb8cf53fe43a99cab41bbcc7821b0
> 72ms
> [220622] MH

- BOJ/Dynamic_Programming/2579-계단_오르기-YJ.py
https://www.acmicpc.net/source/44872037
재밌다(아님)
> 68ms
> [220622] YJ

- BOJ/Data_Structure/11726-2xn_타일링-GH.py
피보나치~~ ~~
> http://boj.kr/3fa88e0b5fb5434ab61b1a38d5df84ad
> 72ms
> [220620] GH

- Programmers/거리두기_확인하기-YJ.py
시간 초과되어서 ,,, 결국 구글링을,, 털썩
bfs 감 떨어졌네.... 🤮
> [220623] YJ

- Programmers/거리두기_확인하기-MH.py
풀다가 냅다 커밋하는 사람 어때.....................................
> [220623] MH

- Programmers/거리두기_확인하기-GH.py
와.. 나 bfs 아무것도 몰랏네..
코로나만 아니엇으면 이 문제가 생기지도 않앗을 텐데..
> [220623] GH

- BOJ/Dynamic_Programming/11727-2xn_타일링_2-MH.py
타일링..그만해주면되.
http://boj.kr/8ea9c119985040d8b250fecb82e706af
> 72ms
> [220624] MH

- Programmers/거리두기_확인하기-NY.py
간만에 풀었는디..
완전 노가다 방식도 틀리고 bfs도 틀린 사람 어때요?
> [220623] NY

- BOJ/Dynamic_Programming/11727-타일링2-YJ.py
https://www.acmicpc.net/source/44950322
n = 5까지 그리고 나서야 규칙파악한 여성
> 72ms
> [220624] YJ

- BOJ/Data_Structure/11727-2xn_타일링-GH.py
규칙만찾으면쉬운데
규칙을찾는게어려움
푸주 ㅋ
두부 ㅋ
> 68ms
> http://boj.kr/802bebdbf48f452199e1fff1c5afd741
> [220624] GH

- Programmers/수식_최대화-YJ.py
> [220625] YJ

- Programmers/수식_최대화-NY.py
> [220625] NY

- Programmers/수식_최대화-MH.py
permutations으로 생긴 연산자 순열을 역순서 우선순위로 쓰는 방법입니다,,
세번째 우선순위로 먼저 split, 두번째 우선순위로 split하고 첫번째 우선순위는 괄호로 처리한 다음에 eval로 계산
근데 eval 쓰는거 별로 안좋다고 하더래요,,,, 어쩔티비
다른 사람 풀이 도움 받았어요,,
> [220626] MH

- Programmers/수식_최대화-YJ.py
이것저것 찾아보다가 이 풀이가 가장 이해가 잘돼서 ^^ .. 적용해봤슴다
> [220626] YJ

- Programmers/수식_최대화-GH.py
와 이거 왤케 어렵고 복잡해
짜증나......................
> [220625] GH

- BOJ/Dynamic_Programming/2407-조합-NY.py
> [220627] NY

- BOJ/Data_Structure/2407-조합-GH.py
꺄아
숨통이 트이는 문제다
> http://boj.kr/ce3de2526c7e4482aeb3c05bb2096af1
> 68ms
> [220627] GH

- BOJ/Dynamic_Programming/2407-조합-YJ.py
nCm = n! / (n - m)! * m!
ㄱㅅㅎㄴㄷ
> [220627] YJ

- Programmers/튜플-MH.py
> [220628] MH

- Programmers/튜플-NY.py
이렇게 비효율적으로 푸는 사람 청 본다고요? 저도 처음 봐요
> [220628] NY

- BOJ/Dynamic_Programming/22857-가장_긴_짝수_연속한_부분_수열_(small)-MH.py
아...어렵네.............
어떻게 짝수 홀수 패턴은 찾았는데 슬쩍 보니까 이렇게 푸는게 아닌 것 같아요
어려운 DP..
> [220629] MH

- Programmers/빛의_경로_사이클.py
아무래도 사이클이다보니 DFS를 사용하면 되지 않을까요? ㏊㏊㏊
> [220630] YJ

- BOJ/Dynamic_Programming/11053-가장_긴_증가하는_수열-YJ.py
https://www.acmicpc.net/source/45316897
SSAP가능
> 208 ms
> [220701] YJ

- BOJ/Dynamic_Programming/11053-가장_긴_증가하는_부분_수열-NY.py
솔직 고백.. 잘 모르겠어서 고민하다가 예전에 내가 짠 코드 다시 참고함 ㅜㅜ..
https://www.acmicpc.net/source/45330310
> [220701] NY

- Programmers/전화번호_목록-MH.py
첨에 dp로 풀었다가 개같이 멸망
알고보니 해시 문제더라구요
담에 해시로 풀어봐야지
> [220702] MH

- Programmers/튜플-GH.py
이쯤 되면 정규표현식 마스터 했을 법도 한데..
할 때마다 계속 공부해야 됨..
2점밖에안주다니짜다짜
> [220628] GH

- BOJ/Dynamic_Programming/1912-연속합-MH.py
문제 이해 잘못해서 짱유진언니가 도와줌요
근데 dp... 아직 적응안된다 킥..
http://boj.kr/fbe38a8fb42e4ca581ff974d35c6a2c0
> 128ms
> [220704] MH

- BOJ/Dynamic_Programming/1912-연속합-YJ.py
https://www.acmicpc.net/source/45511352
> 124ms
> [220704] YJ

- Programmers/빛의_경로_사이클-GH.py
- Programmers/전화번호_목록-GH.py
지난주 밀린 거 프로그래머스부터 풀엇어요
절대 백준이 싫고 짜증나서 내일 풀 예정은 아니에요..
사이클은 dfs로 푼 다른 사람 거.. 보고.... 공부햇어요
로직 짜는 것까지는 어쉉쉉 됏는데 코드가 어쉉쉉해서.. 참고햇습니다!!
> [220704] GH

- Programmers/프린터-MH.py
> [220705] MH

- Programmers/프린터-NY.py
어 이거.. 분명 푼건데.. 나 왜 틀리지.. 모르겠어요 휑.. 나 너무 어렵게 생각했나..? ...?
> [220705] NY

- Programmers/프린터-YJ.py
> [220706] YJ

- BOJ/Dynamic_Programming/11055-가장_큰_증가_부분_수열-YJ.py
> [220707] YJ

- BOJ/Dynamic_Programming/11055-가장_큰_증가_부분_수열-MH.py
dp야 우리 언제 친해질래?
196ms
> http://boj.kr/1f442f54f1864fdc8868f6d39d2b17e5
> [220706] MH

- BOJ/Data_Structure/11053-가장_긴_증가하는_부분_수열-GH.py
- BOJ/Data_Structure/11055-가장_큰_증가_부분_수열-GH.py
- BOJ/Data_Structure/1912-연속합-GH.py
- BOJ/Data_Structure/22857-가장_긴_짝수_연속한_부분_수열(small)-GH.py
- Programmers/프린터-GH.py
풀어놓고 커밋만 해 둿던 것까지 와다다 올립니다..
디피 문제들은 구글 참고해서 많이 풀엇더용..
대충 푸는 방법은 알 것 같은데 문제마다 디테일이 달라져서
그거 잘 생각해서 풀어야 할 것 같아여..
나 정말 디피 어려워햇네.. ㅜ
> [220706] GH

- Programmers/가장_큰_수-GH.py
어라 이게 되네..
대부분.. 이렇게 많이 풀엇더라고요
글고 유진언니 말대로 cmp_to_key 풀이 진짜 싱기방기뿡뿡방기..
> [220707] GH

- Programmers/가장_큰_수-MH.py
아 탈골..탈골...탍골탈골탈골........
쉬워보이는데 왤케 복잡한데 뭔데
> [220707] MH

- Programmers/1890-점프-MH.py
dp 문제인줄 알면서도 냅다 재귀로 풀고 틀린 나 제법 멋져요
http://boj.kr/5ce173d3054e489484ceafbad4184f5d
> 176ms
> [220708] MH

- BOJ/Dynamic_Programming/1890_점프-YJ.py
https://www.acmicpc.net/source/45755705
그것이.. 점프니깐
> 72ms
> [220708] YJ

- Programmers/소수_찾기_2-MH.py
굉장히 돌고돌아서 푼 것같은데..
다음에 set 특성 이용해서 다시 풀어봐야겠어요
> [220709] MH

- Programmers/소수_찾기2-YJ.py
> [220709] YJ

- Programmers/가장_큰_수-MH.py
> [220710] MH

- BOJ/Dynamic_Programming/9465-스티커-YJ.py
https://www.acmicpc.net/source/45906667
시간.. 실ㅎㅘ?
> 1752ms
> [220711] YJ

- BOJ/Dynamic_Programming/9465-스티커-NY.py
이상하다 ㅜㅜ 이거 예전에 맞춘건디...
거의 다 푼거 같은디.... 도대체 예전에 어케 푼거지.. 코드도 이거 절반이던데... 멍
> [220711] NY

- BOJ/Data_Structure/1890-점프-GH.py
- BOJ/Data_Structure/9465-스티커-GH.py
- Programmers/소수_찾기_2-GH.py
- Programmers/조이스틱-GH.py
어ㅜ 요즘 넘 바빠서 풀기만 하고 커밋을 못해 가지구.. (머쓱
쪼이스틱.. 처음에 짤 때 제법 유니티 하는 기분이엇는데..!!!
안 돼서 젤 유명한 코드 풀이 보고 공부햇뜹니다!!
> [220712] GH

- Programmers/조이스틱-YJ.py
> [220712] YJ

- BOJ/Data_Structure/15486_퇴사_2-GH.py
디피 니가 먼데
나를 화나게 해..
이럴수록 널 이기고 싶다는 생각보다는
그냥 치우고싶어짐
> [220713] GH

- BOJ/Dynamic_Programming/2156-포도주_시식-MH.py
> [220715] MH

- Programmers/예상_대진표-YJ.py
오랜만에 풀었는데 문제가 쉬운거라 기분이 조크든여 ㅎ!!!!
> [220717] YJ

- BOJ/Data_Structure/2156-포도주_시식-GH.py
- Programmers/게임_맵_최단거리-GH.py
> [220715] GH

- BOJ/Dynamic_Programming/10844-쉬운_계단_수-YJ.py
https://asxpyn.tistory.com/52
예전에 푼 풀이 양심없이 제출 ^0^
> [220718] YJ

- Programmers/순위_검색-GH.py
ㅎ ㅏ..
효율성 부분에서 통과가 안 돼서
답을 보고야 말앗습니다..
카카오는 못 들어가게 됏다
> [220719] GH

- BOJ/Data_Structure/2294-동전_2-GH.py
- Programmers/후보키-GH.py
e동전은!!
> 400ms
어우 프로그래머스 왤케 어려워요..???
풀다가 조건 짜고 이런 거에서 제법 막혀서 구글의 힘을 빌렷슴다...
> [220721] GH

- BOJ/Dynamic_Programming/2294-동전_2-YJ.py
https://www.acmicpc.net/source/46390050
> 456ms
> [220720] YJ
